import { HelpRole, type HelpArticle, type FaqItem } from "./help.types";

const { Client, Artist, Owner, Issuer } = HelpRole;

export const HELP_ARTICLES: HelpArticle[] = [
  // ── Client ──────────────────────────────────────────────────────────────
  {
    id: "client-book-appointment",
    roles: [Client],
    title: "Book an appointment",
    route: "/book",
    keywords: ["booking", "request", "artist", "schedule a tattoo", "new appointment", "reference images", "upload photo"],
    summary: "Request a tattoo appointment by picking an artist, a date, and how long the session should be.",
    steps: [
      "If a banner asks you to verify your email, click \"Resend verification email\" (you must verify before your booking is finalized).",
      "In the \"Book an appointment\" card, choose an artist, a date, and an appointment duration.",
      "Optionally add notes, and attach up to 6 reference images (JPEG, PNG, or WebP) under \"Reference images\" — click the box to pick photos from your device.",
      "Submit the booking request.",
      "Check \"My Bookings\" below the form to see your pending and upcoming appointments.",
    ],
    tips: [
      "Your booking is a request, not a confirmed slot — the studio replies within 24 hours.",
      "Reference images upload as soon as you pick them — wait for each thumbnail to finish before submitting.",
    ],
    relatedArticleIds: ["client-cancel-booking"],
  },
  {
    id: "client-cancel-booking",
    roles: [Client],
    title: "Cancel an appointment",
    route: "/book",
    keywords: ["cancel appointment", "cancel booking", "refund", "forfeit deposit", "notice window"],
    summary: "Cancel one of your own upcoming appointments directly from My Bookings, with a preview of what happens to your deposit.",
    steps: [
      "Under \"My Bookings\", find the appointment and click \"Cancel appointment\".",
      "Read the message: cancelling with enough notice refunds your deposit in full; cancelling too close to the appointment may forfeit some or all of it.",
      "Click \"Yes, cancel\" to confirm, or \"Keep booking\" to back out.",
    ],
    tips: [
      "Cancellation can only be self-served for a Pending or Confirmed appointment — once it's Completed or marked as a no-show, contact the studio directly.",
      "The refund outcome shown is a preview; the studio's cancellation policy (notice window and late-cancel refund %) is what's actually applied.",
    ],
    relatedArticleIds: ["client-reschedule-booking"],
  },
  {
    id: "client-reschedule-booking",
    roles: [Client],
    title: "Reschedule an appointment",
    route: "/book",
    keywords: ["reschedule appointment", "change date", "move appointment", "notice window"],
    summary: "Move one of your own upcoming appointments to a new date, time, or duration directly from My Bookings.",
    steps: [
      "Under \"My Bookings\", find the appointment and click \"Reschedule\".",
      "Pick a new date & time and duration — a live availability check appears for the new slot.",
      "Click \"Confirm reschedule\".",
    ],
    tips: [
      "Reschedule is only available with enough notice (the studio's configured window, 24 hours by default). Closer than that, the button is disabled and you'll need to contact the studio directly.",
      "Rescheduling doesn't change the appointment's status — a Confirmed appointment stays Confirmed.",
    ],
  },
  {
    id: "client-leave-review",
    roles: [Client],
    title: "Leave a review",
    keywords: ["review", "rate", "rating", "star rating", "feedback", "leave a review"],
    summary: "Rate and review a studio or artist after a completed appointment with them — from a studio's or artist's public profile page.",
    steps: [
      "Go to the studio's page (/s/{slug}) or the artist's page (/artist/{slug}) and scroll to \"Reviews\".",
      "If you have a completed appointment there that you haven't reviewed yet, the \"Write a review\" form appears.",
      "If you have more than one eligible visit, pick which one you're reviewing from the dropdown.",
      "Pick a star rating and write your review (minimum 10 characters), then click \"Post Review\".",
    ],
    tips: [
      "You can leave a new review each time you have a completed appointment there — it's not a one-time-only thing. You just can't review the same visit twice.",
      "You can leave both a studio review and an artist review from the same completed appointment — they're independent.",
      "If you don't see the review form, you don't yet have a completed appointment there — the studio/artist needs to mark your appointment \"Completed\" first.",
    ],
    relatedArticleIds: ["client-book-appointment"],
  },
  {
    id: "client-my-studios",
    roles: [Client],
    title: "Switch between studios you're a client at",
    route: "/my-studios",
    keywords: ["multiple studios", "switch studio", "leave studio", "active studio"],
    summary: "Lists every studio you've booked with, shows which one is currently active, and lets you switch between them or leave one.",
    steps: [
      "Browse your list of studios, each showing its name, city, and whether it's your current \"Active\" studio.",
      "Click \"Switch\" on a studio to make it your active studio.",
      "Click the \"⋮\" menu on a studio to view its public profile, manage notification settings, or leave the studio.",
      "Click \"Discover\" (top right) to find and join a new studio.",
    ],
    tips: ["Leaving a studio doesn't delete your history — your appointment records are kept and you can rejoin any time."],
  },
  {
    id: "client-designs",
    roles: [Client],
    title: "View your tattoo designs",
    route: "/designs",
    keywords: ["design drafts", "artwork", "review design"],
    summary: "Shows the tattoo design drafts your artist has uploaded for you to review.",
    steps: [
      "Use the search box to filter designs by title (only shown once you have designs).",
      "Browse your design list — designs waiting on your feedback (\"Changes Requested\") are shown first.",
      "Click a design to open it and review its images.",
    ],
    tips: ["If the list is empty, your artist just hasn't uploaded anything yet — you don't need to do anything."],
    relatedArticleIds: ["client-design-approve"],
  },
  {
    id: "client-design-approve",
    roles: [Client],
    title: "Approve a design or request changes",
    route: "/designs",
    keywords: ["approve", "request changes", "reject design", "design revision"],
    summary: "Look at the artwork your artist uploaded and tell them whether it's ready or needs changes.",
    steps: [
      "Open a design and review each version (revision) shown, including its image.",
      "If a banner says your artist is waiting for feedback, review the latest version.",
      "Click \"Approve\" to accept a version, or \"Request Changes\" to ask for edits.",
      "If requesting changes, optionally describe what to change, then click \"Submit\".",
    ],
    tips: ["Only versions that aren't already approved show the Approve / Request Changes buttons."],
    relatedArticleIds: ["client-designs"],
  },
  {
    id: "client-intake-submit",
    roles: [Client],
    title: "Fill out an intake form",
    route: "/forms/intake/new",
    keywords: ["medical history", "health form", "allergies"],
    summary: "Send your artist your medical history and any health details before your session.",
    steps: [
      "Fill in the \"Medical history & notes\" box (allergies, skin conditions, medications, etc.) — at least 10 characters.",
      "Optionally link the form to one of your upcoming appointments.",
      "Optionally paste a link to an attachment (photo or document).",
      "Click \"Submit Intake Form\".",
    ],
    relatedArticleIds: ["client-intake-list"],
  },
  {
    id: "client-intake-list",
    roles: [Client],
    title: "Find your submitted intake forms",
    route: "/forms/intake",
    keywords: ["intake history", "draft form", "submitted"],
    summary: "Lists all the intake forms you've submitted to the studio, showing which are done and which are still drafts.",
    steps: [
      "Browse your list of intake forms — each shows a headline, date, and \"Submitted\" or \"Draft\" badge.",
      "Click \"Submit intake form\" (top right) to fill out a new one.",
      "Click any form in the list to open its details.",
    ],
    relatedArticleIds: ["client-intake-submit"],
  },
  {
    id: "client-consent-sign",
    roles: [Client],
    title: "Sign a consent form",
    route: "/forms/consent/new",
    keywords: ["digital signature", "sign consent", "agreement"],
    summary: "Digitally sign the consent agreement for an upcoming appointment before your tattoo session. The full consent text is shown on the page so you can read exactly what you're agreeing to before you sign.",
    steps: [
      "Read the consent agreement shown at the top of the page in full.",
      "Select the appointment you're signing consent for from the dropdown.",
      "Type your full legal name in the \"Digital signature\" box to sign.",
      "Click \"Sign Consent Form\".",
    ],
    warnings: ["You can only sign one consent form per appointment — a PDF copy is generated and attached automatically once you sign.", "The exact wording you agreed to is saved with your signature, so a past consent always shows what you actually agreed to even if the studio later updates its consent text."],
    relatedArticleIds: ["client-consent-list"],
  },
  {
    id: "client-consent-list",
    roles: [Client],
    title: "Find your signed consent forms",
    route: "/forms/consent",
    keywords: ["consent history", "signed", "pending consent"],
    summary: "Lists the consent forms tied to your appointments and whether each one has been signed yet.",
    steps: [
      "Browse the list — each row shows the appointment and a \"Signed\" or \"Pending\" badge with the date.",
      "Click \"Sign consent form\" (top right) to sign a new one.",
      "Click any row to view that form's details, including the exact consent text you agreed to at the time you signed.",
    ],
    relatedArticleIds: ["client-consent-sign"],
  },
  {
    id: "client-profile",
    roles: [Client],
    title: "Update your profile and body map",
    route: "/clients/me",
    keywords: ["body map", "tattoo history", "sharing", "contact info"],
    summary: "Your personal profile — contact details, where on your body you have or want tattoos, your past tattoo history, and whether other studios can see your profile.",
    steps: [
      "On the \"Profile\" tab, view your email and phone, click \"Edit\" on the Body Map to mark locations, then \"Save\".",
      "Switch to the \"Tattoo History\" tab to see your completed tattoos with photos and descriptions.",
      "Switch to the \"Sharing\" tab to turn on or off letting other studios reuse your profile information.",
    ],
  },
  {
    id: "client-deposit-pay",
    roles: [Client],
    title: "Pay a deposit (card or cash)",
    route: "/pay/:paymentId",
    keywords: ["pay deposit", "checkout", "card payment"],
    summary: "Securely authorize a deposit payment by card for your appointment.",
    steps: [
      "Review the deposit amount shown.",
      "Enter your card details in the payment box.",
      "Click \"Authorise deposit\".",
    ],
    tips: ["Your card isn't charged immediately — it's authorised, and the studio captures the payment closer to your appointment. Payment is by card, or by cash arranged with the studio."],
  },
  {
    id: "client-verify-email",
    roles: [Client],
    title: "Verify your email address",
    route: "/verify-email",
    keywords: ["email verification", "confirm email"],
    summary: "Automatically confirms your email address when you click the verification link sent to your inbox.",
    steps: [
      "Click the verification link in your email, which opens this page.",
      "Wait while the app confirms your email automatically.",
      "If successful, click \"Sign in\" to continue; if it fails, go back to login and request a new link.",
    ],
    warnings: ["If the link has expired or is invalid, verification fails and you must request a new email — the old link cannot be reused."],
  },
  {
    id: "client-change-password",
    roles: [Client, Artist, Owner, Issuer],
    title: "Change your password",
    route: "/account/change-password",
    keywords: ["password", "account security"],
    summary: "Update your account password.",
    steps: [
      "Enter your current password.",
      "Enter a new password (at least 8 characters, with an uppercase letter and a number, different from your current one).",
      "Re-enter the new password to confirm.",
      "Click \"Change password\".",
    ],
    relatedArticleIds: ["client-change-email"],
  },
  {
    id: "client-change-email",
    roles: [Client, Artist, Owner, Issuer],
    title: "Change your email address",
    route: "/account/change-email",
    keywords: ["email", "change email", "account security", "sign-in email"],
    summary: "Switch the email address you use to sign in.",
    steps: [
      "Enter your current password.",
      "Enter your new email address.",
      "Click \"Send confirmation link\".",
      "Open the confirmation email sent to your NEW address and click the link — your email doesn't change until you confirm it.",
    ],
    tips: [
      "Your current email stays active until you confirm the new one, so you won't be locked out mid-change.",
      "A notice is sent to your old email when the change completes, in case it wasn't you.",
    ],
    relatedArticleIds: ["client-change-password"],
  },

  // ── Artist ──────────────────────────────────────────────────────────────
  {
    id: "artist-schedule",
    roles: [Artist],
    title: "View and manage your schedule",
    route: "/schedule",
    keywords: ["calendar", "weekly schedule", "appointments"],
    summary: "Shows your appointments for one week at a time, organized by day, so you can see your schedule at a glance.",
    steps: [
      "Open Schedule from the menu.",
      "Use the left/right arrows to move to the previous or next week.",
      "Click \"Today\" to jump back to the current week.",
      "Click any appointment card to open its full details.",
    ],
    tips: ["Days with no appointments show \"No appointments\"; the current day is highlighted with a \"Today\" badge."],
  },
  {
    id: "artist-appointment-detail",
    roles: [Artist],
    title: "Open an appointment's details",
    route: "/schedule",
    keywords: ["confirm", "reschedule", "cancel", "no-show", "complete appointment"],
    summary: "Shows the full details of a single appointment — client, date/time, duration, status, and deposit — plus actions to move it forward.",
    steps: [
      "Review the client, date/time, duration, status, and deposit info.",
      "Click \"Add to Calendar\" to download an .ics file for the appointment.",
      "Click \"Confirm appointment\" or \"Mark as complete\" to advance its status.",
      "Click \"Reschedule\" to pick a new date/time.",
      "Click \"Mark no-show\" if the client didn't attend, or \"Cancel appointment\" and confirm if it needs to be cancelled.",
    ],
    tips: ["The client's name is a link straight to their client profile."],
    warnings: ["Cancelling an appointment cannot be undone."],
  },
  {
    id: "artist-clients",
    roles: [Artist],
    title: "Find a client you're working with",
    route: "/clients",
    keywords: ["client search", "client list"],
    summary: "A searchable list of all clients in your studio.",
    steps: [
      "Open Clients from the menu.",
      "Type a name or email in the search box to filter the list.",
      "Click \"New Client\" to add a client.",
      "Click any row (or its \"View\" button) to open that client's profile.",
    ],
  },
  {
    id: "artist-client-detail",
    roles: [Artist],
    title: "View a client's profile and tattoo history",
    route: "/clients",
    keywords: ["client profile", "medical notes", "cross-studio"],
    summary: "A client's full profile — contact info, health details, body map, forms, and appointment history — all in one place.",
    steps: [
      "Open a client from the Clients list.",
      "Click \"Edit Profile\" (or \"Add Profile\" if none exists yet) to enter date of birth, allergies, and medical notes, then \"Save Profile\".",
      "Switch between the Profile, Tattoo History, Forms, and Appointments tabs.",
      "On the Profile tab, click \"Edit\" next to Body Map to mark tattoo locations, then \"Save\".",
      "In the Forms tab, click an intake or consent form entry to open its full detail.",
    ],
    tips: ["A \"Cross-Studio\" tab appears automatically if the client has shared tattoo history from other studios on the app."],
  },
  {
    id: "artist-designs",
    roles: [Artist],
    title: "View designs assigned to you",
    route: "/designs",
    keywords: ["design projects", "changes requested"],
    summary: "Your list of tattoo design projects, showing which ones are waiting on your next move.",
    steps: [
      "Open Designs from the menu.",
      "Use the search box to filter by design title.",
      "Designs marked \"Changes Requested\" are automatically pulled to the top since they need your attention.",
      "Click a design card to open it and see its revisions, or click \"New Design\" to start a new one.",
    ],
    relatedArticleIds: ["artist-create-design", "artist-upload-revision"],
  },
  {
    id: "artist-create-design",
    roles: [Artist],
    title: "Create a new design for a client",
    route: "/designs/new",
    keywords: ["new design", "start design"],
    summary: "Start a new tattoo design project for a client so you can upload artwork for their approval.",
    steps: [
      "Open Designs and click \"New Design\".",
      "Select the Client this design is for.",
      "Select the Artist assigned to it.",
      "Enter a Title, and optionally a Description (style, placement, concept).",
      "Click \"Create Design\".",
    ],
    relatedArticleIds: ["artist-upload-revision"],
  },
  {
    id: "artist-upload-revision",
    roles: [Artist],
    title: "Upload a revised design",
    route: "/designs",
    keywords: ["upload artwork", "revision", "new version"],
    summary: "Upload a new version of artwork to an existing design for the client to review.",
    steps: [
      "From a design's page, click \"Upload Revision\".",
      "Click the upload area and choose an image file (JPEG, PNG, or WebP only).",
      "Optionally add notes describing what changed in this revision.",
      "Click \"Upload Revision\" to submit it.",
    ],
    tips: ["The button label shows progress (\"Getting upload URL…\", \"Uploading file…\", \"Saving revision…\") while it uploads."],
  },
  {
    id: "artist-share-design",
    roles: [Artist, Owner],
    title: "Share a design link with a client",
    keywords: ["share link", "public link", "revoke link"],
    summary: "Generate a link so someone without an app account can view a specific design revision.",
    steps: [
      "Open a design and find the revision you want to share.",
      "Click the \"Share\" button on that revision.",
      "Once the link generates, click the copy icon to copy it and send it to whoever needs to view the design.",
      "Click \"Revoke link\" if you want to disable it early.",
    ],
    warnings: ["The share link expires automatically after 30 days; revoking it also cannot be undone — you'd need to generate a new link."],
  },
  {
    id: "artist-intake-view",
    roles: [Artist],
    title: "Review a client's intake form",
    route: "/forms/intake",
    keywords: ["review medical history", "health flags"],
    summary: "Review a client's medical/health intake information that they filled out before their appointment.",
    steps: [
      "Open the client's profile and go to the Forms tab, or open Intake Forms from the menu.",
      "Click the intake form you want to review.",
      "Check the \"Submitted\" or \"Draft\" status at the top.",
      "Review the medical history section — personal info, health flags (allergies, blood conditions, etc.), and any attached file.",
    ],
    tips: ["A form still shows as \"Draft\" if the client hasn't submitted it yet."],
  },
  {
    id: "artist-consent-view",
    roles: [Artist],
    title: "Review a client's signed consent form",
    route: "/forms/consent",
    keywords: ["review signature", "consent document"],
    summary: "Review a client's signed consent form for an appointment, including their signature and any attached document.",
    steps: [
      "Open the client's profile and go to the Forms tab, or open Consent Forms from the menu.",
      "Click the consent form you want to review.",
      "Check the \"Signed\" or \"Pending\" status, client, and linked appointment.",
      "View the digital signature and, if attached, open or download the consent document.",
      "The \"Consent agreement (as signed)\" section shows the exact text the client agreed to at the time — the stored snapshot, not the studio's current wording — so a past consent is always an accurate record.",
    ],
  },
  {
    id: "artist-notifications",
    roles: [Artist],
    title: "Check your notifications",
    keywords: ["bell icon", "alerts", "unread"],
    summary: "The bell icon in the header shows your recent alerts (like new bookings or form submissions) and how many are unread.",
    steps: [
      "Click the bell icon in the top header.",
      "Browse the most recent notifications in the dropdown.",
      "Click a notification to see its full details.",
      "Click \"View all\" to see your complete notification history.",
    ],
    tips: ["Opening the bell automatically clears the unread count badge."],
  },

  // ── Owner ───────────────────────────────────────────────────────────────
  {
    id: "owner-dashboard",
    roles: [Owner],
    title: "Understand your dashboard",
    route: "/dashboard",
    keywords: ["home screen", "overview", "stats"],
    summary: "Your studio's home screen — a snapshot of today's and this week's appointments, deposits still owed, and any cash payments waiting to be collected.",
    steps: [
      "Open Dashboard from the menu.",
      "Check the banner at the top if your subscription needs attention (trial ending, payment failed, etc.) and click its button to fix it.",
      "Review the stat boxes — Today's appointments, This Week's appointments, and Deposits Due.",
      "Scroll to \"Today\" to see today's bookings, or click \"View schedule\" for the full calendar.",
      "If a client owes cash, they appear under \"Awaiting Cash\" — click the confirm button once you've physically received the money.",
    ],
    tips: ["The \"+ Book Appointment\" button in the top right takes you straight to the Schedule to add a new appointment."],
  },
  {
    id: "owner-artists-add",
    roles: [Owner],
    title: "Add an artist to your studio",
    route: "/artists/new",
    keywords: ["new artist", "hire artist", "hourly rate", "invite", "set password", "resend invite"],
    summary: "Add a new tattoo artist to your studio.",
    steps: [
      "Go to Artists and click \"New Artist\".",
      "Enter the artist's first and last name and email address.",
      "Optionally list their specializations (e.g. Traditional, Realism).",
      "Optionally set an hourly rate — used to calculate percentage-based deposits.",
      "Click \"Create Artist\".",
    ],
    tips: [
      "The hourly rate only matters if you use percentage-based deposit rules for this artist.",
      "You don't set a password for the artist. They get an automatic email with a link to set their own password — it expires after 1 hour.",
      "If the artist says they never received that email, open their profile and click \"Resend invite\" next to their email address.",
    ],
  },
  {
    id: "owner-artists-list",
    roles: [Owner],
    title: "Manage your artists",
    route: "/artists",
    keywords: ["artist list", "edit artist", "delete artist"],
    summary: "Lists every artist working at your studio, with tools to search, filter, edit, or remove them.",
    steps: [
      "Go to Artists to see the full list.",
      "Use the search box to find an artist by name or email, or click a specialization pill to filter.",
      "Click \"Edit\" on a row to open that artist's profile, or \"New Artist\" to add one.",
      "To remove an artist, click \"Delete\", then \"Confirm\".",
    ],
    warnings: ["Deleting an artist cannot be undone from this screen."],
  },
  {
    id: "owner-artist-portfolio",
    roles: [Owner, Artist],
    title: "Add portfolio images and tag their style",
    route: "/artists",
    keywords: ["portfolio", "upload image", "tattoo style", "style tag", "discover filter", "no portfolio work"],
    summary: "Upload work to an artist's portfolio and tag each image with a tattoo style so it shows up in the public Discover page's style filters.",
    steps: [
      "Open an artist's profile and click the \"Portfolio\" tab.",
      "Click \"Add image\" and upload the photo.",
      "For each image, use the style dropdown to pick a tattoo style (e.g. Traditional, Realism, Blackwork).",
      "Click the dropdown again at any time to change or clear an image's style.",
    ],
    tips: [
      "The Discover page's style filters only match an image's own style tag — an artist's \"Specializations\" text on their profile does not make their work appear under a style filter.",
      "An image left without a style still shows in the artist's portfolio, but it won't appear when a client filters Discover by style.",
    ],
    relatedArticleIds: ["owner-artists-list"],
  },
  {
    id: "owner-clients-add",
    roles: [Owner],
    title: "Add a client manually",
    route: "/clients/new",
    keywords: ["new client", "walk-in client"],
    summary: "Add a new client record to your studio.",
    steps: [
      "Go to Clients and click \"New Client\".",
      "Enter the client's first and last name and email address.",
      "Optionally enter a phone number.",
      "Click \"Create Client\".",
    ],
  },
  {
    id: "owner-clients-list",
    roles: [Owner],
    title: "Manage your clients",
    route: "/clients",
    keywords: ["client list", "client search"],
    summary: "Lists all clients in your studio so you can search and open their profiles.",
    steps: [
      "Go to Clients to see the full list.",
      "Use the search box to find a client by name or email.",
      "Click \"View\" on any row (or click the row) to open that client's profile.",
      "Click \"New Client\" to add a new one.",
    ],
  },
  {
    id: "owner-designs",
    roles: [Owner],
    title: "Review and manage all studio designs",
    route: "/designs",
    keywords: ["all designs", "design tracking"],
    summary: "Shows every tattoo design uploaded across your studio, so you can track which ones are approved, pending, or need changes.",
    steps: [
      "Go to Designs to see all designs.",
      "Designs the artist needs to revise (\"Changes Requested\") are automatically shown at the top.",
      "Use the search box to find a design by title.",
      "Click a design card to open its details, or \"New Design\" to upload one.",
    ],
  },
  {
    id: "owner-deposit-rules",
    roles: [Owner],
    title: "Set up deposit rules",
    route: "/deposit-rules",
    keywords: ["deposit percentage", "fixed deposit"],
    summary: "Deposit rules define how much clients must pay upfront to secure a booking — either a fixed amount or a percentage.",
    steps: [
      "Go to Deposit Rules to see all your rules.",
      "Click \"New Rule\" to create one, or click an existing rule to view/edit it.",
    ],
    tips: ["If you haven't created any rules yet, new appointments won't have an automatic deposit amount calculated."],
    relatedArticleIds: ["owner-deposit-rule-create"],
  },
  {
    id: "owner-deposit-rule-create",
    roles: [Owner],
    title: "Create a new deposit rule",
    route: "/deposit-rules/new",
    keywords: ["new deposit rule", "percentage deposit", "cancellation policy", "notice window", "late cancellation refund"],
    summary: "Create a new deposit rule that determines how much of a deposit clients pay when booking, and your studio's cancellation policy.",
    steps: [
      "Go to Deposit Rules and click \"New Rule\".",
      "Enter a name for the rule (e.g. \"Standard Deposit\").",
      "Choose \"Fixed amount\" (a set euro amount) or \"Percentage\" (a % of the session cost).",
      "Enter the amount or percentage.",
      "Optionally set a \"Cancellation notice window\" — how many hours' notice a client must give to self-cancel without forfeiting their deposit. Leave blank to use the 24-hour platform default.",
      "Optionally set \"Refund if cancelled late\" — the percentage of the deposit refunded if a client cancels within that window. 0% (the default) forfeits the deposit entirely.",
      "Leave \"Active\" checked if you want the rule to apply immediately, then click \"Create Rule\".",
    ],
    tips: [
      "Percentage rules must be between 0.01% and 100%.",
      "The cancellation notice window also gates client self-reschedule, not just self-cancel.",
    ],
  },
  {
    id: "owner-schedule",
    roles: [Owner],
    title: "View the studio-wide schedule",
    route: "/schedule",
    keywords: ["studio calendar", "all appointments"],
    summary: "Shows every appointment booked across your whole studio, organized by week and day.",
    steps: [
      "Go to Schedule.",
      "Use the left/right arrows to move between weeks, or click \"Today\" to jump back to the current week.",
      "Click any appointment card to see more details or take action on it.",
    ],
  },
  {
    id: "owner-payments",
    roles: [Owner],
    title: "Track deposits and payments",
    route: "/payments",
    keywords: ["payment list", "cash pending", "paid"],
    summary: "Lists every payment recorded in your studio — card and cash — so you can track what's been paid, is pending, or refunded.",
    steps: [
      "Go to Payments to see the list.",
      "Use the search box to find payments by client name, or click a status pill (e.g. Pending, Cash Pending, Paid) to filter.",
      "Click \"New payment\" to record a new one.",
      "Click \"View\" on any row to open its details, or \"Load more\" to see older payments.",
    ],
  },
  {
    id: "owner-payment-create",
    roles: [Owner],
    title: "Create a payment request manually",
    route: "/payments/new",
    keywords: ["new payment", "record payment", "checkout link"],
    summary: "Record a new deposit payment for an appointment, either by card or cash.",
    steps: [
      "Go to Payments and click \"New payment\".",
      "Search and select an appointment that has a pending deposit.",
      "Choose \"Card\" or \"Cash\" as the payment method.",
      "Confirm or adjust the deposit amount.",
      "Click \"Create card payment\" or \"Record cash payment\".",
      "For card payments, copy the checkout link and send it to the client; for cash, it stays pending until you confirm receipt later.",
    ],
    tips: ["If no deposit rule applies to the appointment, you'll need to type in the amount manually."],
  },
  {
    id: "owner-cash-confirm",
    roles: [Owner, Artist],
    title: "Confirm a cash deposit was received",
    keywords: ["cash received", "confirm payment"],
    summary: "Mark a cash deposit as officially received once the client has physically paid.",
    steps: [
      "Open the payment's detail page (from Payments list, or the \"Awaiting Cash\" section on the Dashboard).",
      "Once you've collected the cash from the client, click \"Confirm cash received\".",
      "The payment status updates to Paid.",
    ],
    warnings: ["Only confirm once you have actually received the cash — this action records the payment as collected."],
  },
  {
    id: "owner-studio-profile",
    roles: [Owner],
    title: "Edit your studio profile",
    route: "/studios/me",
    keywords: ["studio settings", "studio name", "address", "description", "nipt", "tax id", "business id"],
    summary: "Edit your studio's public details — name, address, phone, Instagram, description — and your business tax ID (NIPT), which clients don't see but is used for invoicing and verification.",
    steps: [
      "Go to Studio Settings.",
      "Click \"Edit\" and update your studio name, address/city, phone number, Instagram handle, or description.",
      "If you haven't added your NIPT yet, enter it in the Business tax ID field — format is one letter, 8 digits, one letter (e.g. L01234567A). Once saved, this field becomes read-only; contact support to change it.",
      "Click \"Save\" to publish the changes.",
    ],
    tips: [
      "Your NIPT is never shown to clients or on your public booking page — it's for invoicing and business verification only.",
    ],
    relatedArticleIds: ["owner-branding", "owner-embed", "owner-qr-code", "owner-referral"],
  },
  {
    id: "owner-branding",
    roles: [Owner],
    title: "Turn off \"Powered by TattooOS\" branding",
    keywords: ["remove branding", "white label"],
    summary: "This toggle controls whether the \"Powered by TattooOS\" credit is shown on your public booking widget.",
    steps: [
      "Go to Studio Settings and scroll to \"Platform branding\".",
      "Switch the toggle to turn \"Powered by TattooOS\" on or off in your booking widget footer.",
    ],
    tips: ["Removing the branding may require upgrading your plan — if your plan doesn't allow it, the toggle will be disabled with an upgrade note."],
  },
  {
    id: "owner-embed",
    roles: [Owner],
    title: "Get your booking widget embed code",
    keywords: ["embed code", "website widget"],
    summary: "Get a ready-made snippet of code to embed your studio's booking widget on your own website.",
    steps: [
      "Go to Studio Settings and scroll to \"Booking widget\".",
      "Click the copy icon to copy the embed code snippet.",
      "Paste it into your website's HTML where you want the booking widget to appear.",
      "Click \"Open preview\" to see what the widget looks like before embedding it.",
    ],
  },
  {
    id: "owner-qr-code",
    roles: [Owner],
    title: "Download your studio's QR code",
    keywords: ["qr code", "print marketing"],
    summary: "Get a scannable QR code that links directly to your studio's booking page, for business cards, storefronts, or social media.",
    steps: [
      "Go to Studio Settings and scroll to \"Marketing QR code\".",
      "Click \"Download PNG\" or \"Download SVG\" to save the QR code image.",
      "Optionally copy the plain link shown above the QR code to share directly.",
    ],
  },
  {
    id: "owner-referral",
    roles: [Owner],
    title: "Get your referral code",
    keywords: ["invite a studio", "referral link", "free month"],
    summary: "Get a unique referral link and code to share with other tattoo studios — when a new studio signs up and subscribes, both of you get a free month.",
    steps: [
      "Go to Studio Settings and scroll to \"Referral programme\".",
      "If you don't have a code yet, click \"Generate referral code\".",
      "Click the copy icon to copy your referral link and share it.",
      "Track studios that used your code and rewards earned in the stats shown below.",
    ],
  },
  {
    id: "owner-notifications",
    roles: [Owner],
    title: "Review sent notifications",
    route: "/notifications",
    keywords: ["email log", "sms log", "delivery status"],
    summary: "A log of every email and SMS notification your studio has sent to clients, showing whether each one was delivered successfully.",
    steps: [
      "Go to Notifications to see the full log.",
      "Use the Channel dropdown to filter by Email or SMS.",
      "Use the From/To date pickers to narrow the log to a date range.",
      "Click any entry to see its full content.",
    ],
  },
  {
    id: "owner-billing",
    roles: [Owner],
    title: "Understand your plan, trial, and billing",
    route: "/billing",
    keywords: ["subscription", "invoices", "plan usage"],
    summary: "Shows your studio's current subscription plan, status, and usage against your plan's limits, plus options to change or manage your billing.",
    steps: [
      "Go to Billing to see your plan, status, and next renewal or trial end date.",
      "Review the \"Plan usage\" card to see how close you are to your plan's limits.",
      "If you're on a paid card-billed plan, click \"Change plan\" or \"Manage billing\".",
      "If a plan change is scheduled, click \"Keep current plan\" to cancel it before it takes effect.",
    ],
    relatedArticleIds: ["owner-subscribe"],
  },
  {
    id: "owner-subscribe",
    roles: [Owner],
    title: "Choose or change your subscription plan",
    route: "/billing/subscribe",
    keywords: ["upgrade plan", "checkout", "monthly yearly"],
    summary: "Choose or change your studio's subscription plan and pay by card.",
    steps: [
      "Go to Billing and click \"Subscribe\" / \"Upgrade\" / \"Change plan\".",
      "Toggle between Monthly and Yearly billing (yearly usually saves money).",
      "Click a plan card to select it.",
      "Click the button at the bottom to continue to checkout, switch plan, or activate the Free plan.",
    ],
    tips: ["If you'd rather pay by cash, contact support using the link at the bottom of the page instead — your trial keeps running until it's set up."],
    warnings: ["Downgrading an existing card-billed plan takes effect only at the end of your current billing period, and you can't select a new plan while a change is already scheduled."],
  },
  {
    id: "owner-reports",
    roles: [Owner],
    title: "Revenue reports",
    route: "/reports",
    keywords: ["revenue", "trend", "per artist", "earnings", "analytics"],
    summary: "See your studio's revenue trend over the last 12 months and a breakdown of revenue by artist.",
    steps: [
      "Go to Reports to see the revenue trend chart, based on paid deposits over the last 12 months.",
      "Hover over a point on the chart to see that month's exact revenue.",
      "Scroll down to \"Revenue by artist\" for a breakdown of the last 30 days, sorted highest first.",
    ],
    tips: ["Only fully paid deposits (card captured or cash confirmed) count toward these figures — pending or refunded ones don't."],
  },
  // ── Issuer ──────────────────────────────────────────────────────────────
  {
    id: "issuer-dashboard",
    roles: [Issuer],
    title: "Read the platform dashboard",
    route: "/platform",
    keywords: ["platform overview", "mrr", "kpi"],
    summary: "A snapshot of how the whole platform is doing — how many studios, how much revenue, and which studios need attention.",
    steps: [
      "View the KPI cards for totals (Total Studios, Active Subscriptions, MRR, ARPU).",
      "View the pipeline cards (Trialing, Grace Period, Past Due, Cancelled).",
      "Scroll to the MRR chart.",
      "Check \"At-Risk Studios\" and use \"Extend trial\" inline, or click through to that studio.",
    ],
    tips: ["Clicking most KPI cards jumps straight to a pre-filtered Studios or Subscriptions list."],
  },
  {
    id: "issuer-studios",
    roles: [Issuer],
    title: "Oversee all studios",
    route: "/platform/studios",
    keywords: ["studio list", "manage studios"],
    summary: "The full list of every studio on the platform, where you can search, filter, and manage each one.",
    steps: [
      "Search by studio name or slug, and filter by status or plan.",
      "Browse studios, grouped by status.",
      "Click \"View\" to open a studio's full detail page, or use a row's Extend Trial, Activate, Suspend/Reactivate, or Cancel Subscription buttons directly.",
    ],
    tips: ["Use the copy icon next to a studio's slug to quickly copy it."],
  },
  {
    id: "issuer-studio-detail",
    roles: [Issuer],
    title: "Open a single studio's detail",
    route: "/platform/studios",
    keywords: ["studio detail", "owner info"],
    summary: "A full profile of one studio — its info, owner, usage numbers, referral codes, and all the actions you can take on it.",
    steps: [
      "Review the studio info card (slug, city, registered date, branding setting, plan, subscription status).",
      "Review the Studio Overview card (owner name/email, artist/client/appointment counts).",
      "Generate or manage referral codes for this studio.",
      "Use the Actions panel on the right for Extend Trial, Activate, Suspend/Reactivate, or Cancel Subscription.",
    ],
    tips: ["Click \"View public portfolio\" to open the studio's live public page in a new tab."],
  },
  {
    id: "issuer-suspend-studio",
    roles: [Issuer],
    title: "Suspend or unsuspend a studio",
    keywords: ["suspend", "lock out", "reactivate studio"],
    summary: "Temporarily lock a studio out of the platform without deleting anything, or restore access afterward.",
    steps: [
      "Go to the studio's detail page (or its row in the Studios list).",
      "Click \"Suspend Studio\" (or \"Reactivate Studio\" if already suspended).",
      "Read the confirmation message, then click \"Confirm\".",
    ],
    warnings: ["Suspending a studio immediately hides it from Discover and blocks logins for its owner and all its artists — this takes effect right away, though it can be undone anytime with \"Reactivate Studio\"."],
  },
  {
    id: "issuer-plans",
    roles: [Issuer],
    title: "Manage subscription plans",
    route: "/platform/plans",
    keywords: ["plan catalogue", "pricing"],
    summary: "The catalogue of subscription plans studios can sign up for.",
    steps: [
      "Browse existing plans as cards (price, features, usage limits, number of subscribed studios).",
      "Click \"New plan\" to create one.",
      "Click the pencil icon to edit a plan, or the trash icon to delete it, then confirm.",
    ],
    warnings: ["Deleting a plan is permanent and stops new studios from signing up to it — studios already subscribed keep their subscription unaffected."],
  },
  {
    id: "issuer-plan-edit",
    roles: [Issuer],
    title: "Create or edit a plan",
    route: "/platform/plans/new",
    keywords: ["plan price", "usage limits", "feature flags"],
    summary: "Create a new subscription plan or edit an existing one, including its price and usage limits.",
    steps: [
      "Enter the plan Name and the Yearly discount percentage.",
      "Turn on Monthly price and/or Yearly price, entering the price for each.",
      "Toggle feature flags: Allow branding removal.",
      "Set usage limits (Artists, Appointments/mo, Notifications/mo, Storage, Locations) or check \"Unlimited\".",
      "Click Save.",
    ],
    tips: ["A plan must be either fully free (all prices €0) or fully paid — you can't mix a free interval with a paid one."],
  },
  {
    id: "issuer-subscriptions",
    roles: [Issuer],
    title: "Oversee all subscriptions",
    route: "/platform/subscriptions",
    keywords: ["billing oversight", "subscription status"],
    summary: "A full list of every studio's subscription status across the platform, so you can review and manage billing situations one by one.",
    steps: [
      "Filter by status using the chips at the top (Active, Trialing, Grace Period, Past Due, Cancelled, etc.).",
      "Search by studio name or slug.",
      "Sort by trial end date, period end date, or studio name.",
      "Use each row's Extend Trial, Activate, or Cancel Subscription buttons as needed.",
    ],
  },
  {
    id: "issuer-extend-trial",
    roles: [Issuer],
    title: "Extend a studio's trial",
    keywords: ["grant extension", "more trial days"],
    summary: "Give a studio extra time before their trial (or grace period) runs out, without requiring payment.",
    steps: [
      "Find the studio on the Dashboard, Studios list, Subscriptions list, or its detail page.",
      "Click \"Extend Trial (+7 days)\" (shown as \"Grant Extension\" if the trial already expired).",
      "Enter the number of extra days (defaults to 7, 1–90 allowed).",
      "Click \"Confirm\".",
    ],
  },
  {
    id: "issuer-activate-cash-sub",
    roles: [Issuer],
    title: "Activate a subscription paid by cash",
    keywords: ["cash payment", "manual activation"],
    summary: "Mark a studio's subscription as paid when they paid you outside the app, in cash, instead of by card.",
    steps: [
      "Click \"Activate\" on the studio (Dashboard row, Studios list, Subscriptions list, or detail page).",
      "Select the plan they paid for.",
      "Optionally add a note (e.g. the date cash was received).",
      "Click \"Activate subscription\".",
    ],
    tips: ["Only use this for cash payments collected in person — card payments go through the studio's own checkout automatically."],
  },
  {
    id: "issuer-referrals",
    roles: [Issuer],
    title: "Manage platform referral codes",
    route: "/platform/referrals",
    keywords: ["referral code", "generate code"],
    summary: "Create and manage referral codes that let studios invite other studios to join the platform.",
    steps: [
      "Click \"Generate Code\".",
      "Pick the studio the code is for, and optionally set an expiry date.",
      "Click \"Generate\".",
      "From the list, copy, deactivate, reactivate, or delete existing codes; search or filter by Active/Inactive.",
    ],
    tips: ["Each studio can only have one active code at a time — generating a new one automatically deactivates its old one."],
    warnings: ["Deleting a code with zero redemptions cannot be undone. A code that has already been redeemed can't be deleted at all, only deactivated."],
  },
  {
    id: "issuer-reports",
    roles: [Issuer],
    title: "Read monthly industry reports",
    route: "/platform/reports",
    keywords: ["analytics", "plan usage report"],
    summary: "Platform-wide, anonymized statistics (bookings, trial conversion, revenue growth) plus a live table of how each studio's usage compares to their plan limits.",
    steps: [
      "Browse previously generated monthly reports.",
      "Click \"Download\" to save one, or \"Open\" to view it in a new tab.",
      "Click \"Generate Report\" to trigger a new one immediately (60-second cooldown after each trigger).",
      "Scroll down to the \"Plan usage report\" table to see each studio's usage against their plan's limits.",
    ],
    tips: ["Reports contain no studio names or personal data — they're aggregated platform-wide. New reports also generate automatically on the 1st of every month."],
  },
  {
    id: "issuer-feedback",
    roles: [Issuer],
    title: "Read feedback submitted by owners",
    route: "/platform/feedback",
    keywords: ["bug reports", "feature requests", "inbox"],
    summary: "The inbox where bug reports, feature requests, and general feedback sent in by studio users land for you to review.",
    steps: [
      "Filter by type (Bug Report, Feature Request, General) and/or status (Open, Reviewing, Resolved, Dismissed).",
      "Click a feedback card to expand it and read the full message.",
      "Optionally write an internal note (only visible to you, not the sender).",
      "Click a status button to mark it Open, Reviewing, Resolved, or Dismissed.",
    ],
  },
  {
    id: "issuer-help-insights",
    roles: [Issuer],
    title: "Review Help search insights",
    route: "/platform/help-insights",
    keywords: ["help search analytics", "zero-result queries", "missing documentation"],
    summary: "See what studio users searched for in the in-app Help menu, including which searches returned no results — the clearest signal of missing or confusing documentation.",
    steps: [
      "Open Help Insights from the platform nav.",
      "Review the top queries table to see what users look for most.",
      "Review the zero-result queries table — each of these is a documentation or UX gap worth fixing.",
    ],
    tips: ["Data covers a rolling 30-day window and is aggregated across all studios."],
  },
  {
    id: "issuer-audit-log",
    roles: [Issuer],
    title: "Review the platform audit log",
    route: "/platform/audit-log",
    keywords: ["audit log", "admin actions", "compliance", "who did what"],
    summary: "A searchable, cross-tenant log of every trust-sensitive action taken on the platform — studio suspensions, subscription changes, plan edits, referral code changes, and more.",
    steps: [
      "Open Audit Log from the platform nav.",
      "Filter by action, target type, or a date range.",
      "Each row shows when it happened, what happened, what it targeted, which studio (or \"Platform-wide\" for actions with no single studio target), and the actor's role.",
    ],
    tips: ["Entries never contain names, emails, or free text — only IDs, roles, and structural values, so this log is safe to reference without exposing personal data."],
  },
  {
    id: "owner-audit-log",
    roles: [Owner],
    title: "Recent studio activity",
    route: "/studios/me",
    keywords: ["recent activity", "audit", "who did what"],
    summary: "A read-only list of the most recent trust-sensitive actions taken on your studio (e.g. a client-cancelled appointment), shown on your Studio Settings page.",
    steps: [
      "Go to Studio Settings and scroll to \"Recent studio activity\".",
      "Each entry shows the action and when it happened.",
    ],
  },
  {
    id: "artist-owner-send-feedback",
    roles: [Artist, Owner],
    title: "Send feedback",
    keywords: ["feedback", "bug report", "feature request", "report a bug", "attachment", "screenshot", "video"],
    summary: "Report a bug, request a feature, or share general feedback with the team, with an optional screenshot or short video attached.",
    steps: [
      "Click the feedback icon to open \"Send Feedback\".",
      "Choose a Type (Bug Report, Feature Request, or General), add a Title and Description.",
      "Optionally attach up to 3 screenshots or short video clips under \"Attachments\" — click the box to pick files.",
      "Click \"Send Feedback\".",
    ],
    tips: ["Attachments upload as soon as you pick them — wait for each one to finish before submitting."],
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: "faq-trial-length",
    roles: [Owner],
    question: "How long is the free trial, and what happens when it ends?",
    answer: "New studios get a 14-day full-featured trial with no credit card required. After the trial ends, you get a 7-day read-only grace period, and if you still haven't subscribed after that, your studio is suspended until you do.",
    relatedArticleIds: ["owner-billing", "owner-subscribe"],
  },
  {
    id: "faq-grace-period",
    roles: [Owner],
    question: "What is the 7-day grace period, and what can I do during it?",
    answer: "The 7-day grace period starts right after your trial ends. During it, you can still view everything in the app, but you can't make changes (no new bookings, no edits) until you subscribe. A banner reminds you the whole time.",
    relatedArticleIds: ["owner-billing"],
  },
  {
    id: "faq-cash-vs-card",
    roles: [Owner, Client],
    question: "What's the difference between paying by card and paying by cash?",
    answer: "Card payments are authorised at booking and the studio captures the payment later. Cash payments are declared by the client at booking, then the studio or artist confirms it in the app once the cash is physically received. There is no PayPal or other payment method.",
    relatedArticleIds: ["client-deposit-pay", "owner-payment-create"],
  },
  {
    id: "faq-cash-confirm-who",
    roles: [Owner, Artist],
    question: "Who has to confirm a cash deposit was received?",
    answer: "Either the owner or the artist on the appointment can confirm a cash deposit once the client has physically paid.",
    relatedArticleIds: ["owner-cash-confirm"],
  },
  {
    id: "faq-deposit-statuses",
    roles: [Owner, Artist, Client],
    question: "What do the different deposit statuses mean?",
    answer: "Pending means the deposit hasn't been paid yet. Paid means it's been received (card captured or cash confirmed). Refunded means it was paid back to the client. Forfeited means the client kept it forfeited per your studio's cancellation terms.",
    relatedArticleIds: ["owner-payments"],
  },
  {
    id: "faq-client-cancel-refund",
    roles: [Client],
    question: "Do I get my deposit back if I cancel my appointment?",
    answer: "It depends on the studio's cancellation policy. Cancel with enough notice (the studio's configured notice window, 24 hours by default) and you get a full refund. Cancel later than that and you may only get a partial refund, or none at all, depending on the studio's settings.",
    relatedArticleIds: ["client-cancel-booking"],
  },
  {
    id: "faq-design-statuses",
    roles: [Client, Artist, Owner],
    question: "What do the different design statuses mean?",
    answer: "Pending means the client hasn't reviewed the latest version yet. Approved means the client accepted it. Changes Requested means the client asked for edits and it's waiting on the artist. Expired means it went unreviewed too long.",
    relatedArticleIds: ["client-design-approve", "artist-designs"],
  },
  {
    id: "faq-appointment-statuses",
    roles: [Client, Artist, Owner],
    question: "What do the different appointment statuses mean?",
    answer: "Pending means the booking request hasn't been confirmed yet. Confirmed means the studio accepted it. Completed means the session happened. Cancelled means it was called off. No-Show means the client didn't attend.",
    relatedArticleIds: ["artist-appointment-detail"],
  },
  {
    id: "faq-multi-studio",
    roles: [Client],
    question: "I go to more than one studio — can I use one account for both?",
    answer: "Yes. Your account can belong to multiple studios at once. Use the My Studios page to switch which studio is currently active, or to leave one you no longer visit.",
    relatedArticleIds: ["client-my-studios"],
  },
  {
    id: "faq-portable-profile",
    roles: [Client],
    question: "Can a new studio see my tattoo history from another studio?",
    answer: "Only if you turn on sharing for your profile. By default your history stays private to each studio. You control this from the Sharing tab on your profile page. When you opt in, other studios can see your tattoo history — your body-map locations, tattoo photos, and descriptions. They can never see your medical notes, allergies, contact details, payment history, or consent forms, and you can turn sharing off again at any time.",
    relatedArticleIds: ["client-profile"],
  },
  {
    id: "faq-branding-removal",
    roles: [Owner],
    question: "Can I remove the \"Powered by TattooOS\" footer?",
    answer: "Yes, from Studio Settings under \"Platform branding\" — though on some plans this may require upgrading first.",
    relatedArticleIds: ["owner-branding"],
  },
  {
    id: "faq-referral-reward",
    roles: [Owner],
    question: "What do I get for referring another studio?",
    answer: "When a studio you referred signs up with your code and becomes a paying subscriber, you both get a free month added to your subscription.",
    relatedArticleIds: ["owner-referral"],
  },
  {
    id: "faq-share-design-expiry",
    roles: [Client, Artist, Owner],
    question: "How long does a shared design link last?",
    answer: "A shared design link expires automatically 30 days after it's created. It can also be revoked earlier by the artist or owner, which can't be undone — a new link would need to be generated.",
    relatedArticleIds: ["artist-share-design"],
  },
  {
    id: "faq-qr-code-use",
    roles: [Owner],
    question: "What is the studio QR code for?",
    answer: "It's a scannable code that links straight to your studio's public booking page — handy for business cards, your storefront, or social media. Download it as a PNG or SVG from Studio Settings.",
    relatedArticleIds: ["owner-qr-code"],
  },
  {
    id: "faq-notification-channels",
    roles: [Client, Artist, Owner],
    question: "How will I be notified about appointments?",
    answer: "By email and, when a phone number is on file, by SMS. Owners can review every notification sent to their clients from the Notifications page.",
    relatedArticleIds: ["owner-notifications"],
  },
  {
    id: "faq-forgot-password",
    roles: [Client, Artist, Owner, Issuer],
    question: "I forgot my password — what do I do?",
    answer: "Click \"Forgot password?\" on the login screen and enter your email. You'll get a reset link — click it to set a new password. Reset links expire 1 hour after they're sent; if yours has expired, the reset page shows a \"Request a new reset link\" button that takes you straight back to the forgot-password form.",
  },
  {
    id: "faq-issuer-suspend-effect",
    roles: [Issuer],
    question: "What happens to a studio immediately after I suspend it?",
    answer: "It's hidden from Discover right away, and its owner and all its artists are immediately blocked from logging in. Nothing is deleted, and you can reverse it anytime with \"Reactivate Studio\".",
    relatedArticleIds: ["issuer-suspend-studio"],
  },
  {
    id: "faq-issuer-cash-subscription",
    roles: [Issuer],
    question: "How do I activate a studio's subscription if they paid by cash?",
    answer: "Open the studio (from the Dashboard, Studios list, Subscriptions list, or its detail page), click \"Activate\", pick the plan they paid for, and confirm. This is only for cash collected outside the app — card payments activate automatically.",
    relatedArticleIds: ["issuer-activate-cash-sub"],
  },
];
