import { HelpRole, type HelpArticle, type FaqItem } from "./help.types";

const { Client, Artist, Owner, Issuer } = HelpRole;

export const HELP_ARTICLES: HelpArticle[] = [
  // ── Client ──────────────────────────────────────────────────────────────
  {
    id: "client-book-appointment",
    roles: [Client],
    title: "Book an appointment",
    route: "/book",
    keywords: ["booking", "request", "artist", "schedule a tattoo", "new appointment", "reference images", "upload photo", "let studio choose", "any artist", "studio picks artist"],
    summary: "Request a tattoo appointment by picking an artist, a date, and how long the session should be.",
    steps: [
      "If a banner asks you to verify your email, click \"Resend verification email\" (you must verify before your booking is finalized).",
      "In the \"Book an appointment\" card, choose an artist, a date, and an appointment duration.",
      "Or toggle \"Let the studio choose my artist\" if you don't have a preference — the studio will assign one before confirming.",
      "Optionally add notes, and attach up to 6 reference images (JPEG, PNG, or WebP) under \"Reference images\" — click the box to pick photos from your device.",
      "Submit the booking request.",
      "Check \"My Bookings\" below the form to see your pending and upcoming appointments.",
    ],
    tips: [
      "Your booking is a request, not a confirmed slot — the studio replies within 24 hours.",
      "Reference images upload as soon as you pick them — wait for each thumbnail to finish before submitting.",
      "If you let the studio choose, you won't know your artist until the studio assigns one — you'll get an email when they do.",
    ],
    relatedArticleIds: ["client-cancel-booking", "client-messaging"],
  },
  {
    id: "client-cancel-booking",
    roles: [Client],
    title: "Cancel an appointment",
    route: "/book",
    keywords: ["cancel appointment", "cancel booking", "refund", "forfeit deposit", "notice window"],
    summary: "Cancel one of your own upcoming appointments directly from My Bookings, with a preview of what happens to your deposit.",
    steps: [
      "Under \"My Bookings\", find the appointment and click \"Cancel appointment\".",
      "Read the message: cancelling with enough notice refunds your deposit in full; cancelling too close to the appointment may forfeit some or all of it.",
      "Click \"Yes, cancel\" to confirm, or \"Keep booking\" to back out.",
    ],
    tips: [
      "Cancellation can only be self-served for a Pending or Confirmed appointment — once it's Completed or marked as a no-show, contact the studio directly.",
      "The refund outcome shown is a preview; the studio's cancellation policy (notice window and late-cancel refund %) is what's actually applied.",
    ],
    relatedArticleIds: ["client-reschedule-booking"],
  },
  {
    id: "client-reschedule-booking",
    roles: [Client],
    title: "Reschedule an appointment",
    route: "/book",
    keywords: ["reschedule appointment", "change date", "move appointment", "notice window"],
    summary: "Move one of your own upcoming appointments to a new date, time, or duration directly from My Bookings.",
    steps: [
      "Under \"My Bookings\", find the appointment and click \"Reschedule\".",
      "Pick a new date & time and duration — a live availability check appears for the new slot.",
      "Click \"Confirm reschedule\".",
    ],
    tips: [
      "Reschedule is only available with enough notice (the studio's configured window, 48 hours by default). Closer than that, the button is disabled and you'll need to contact the studio directly.",
      "Rescheduling doesn't change the appointment's status — a Confirmed appointment stays Confirmed.",
    ],
  },
  {
    id: "client-leave-review",
    roles: [Client],
    title: "Leave a review",
    keywords: ["review", "rate", "rating", "star rating", "feedback", "leave a review"],
    summary: "Rate and review a studio or artist after a completed appointment with them — from a studio's or artist's public profile page.",
    steps: [
      "Go to the studio's page (/s/{slug}) or the artist's page (/artist/{slug}) and scroll to \"Reviews\".",
      "If you have a completed appointment there that you haven't reviewed yet, the \"Write a review\" form appears.",
      "If you have more than one eligible visit, pick which one you're reviewing from the dropdown.",
      "Pick a star rating and write your review (minimum 10 characters), then click \"Post Review\".",
    ],
    tips: [
      "You can leave a new review each time you have a completed appointment there — it's not a one-time-only thing. You just can't review the same visit twice.",
      "You can leave both a studio review and an artist review from the same completed appointment — they're independent.",
      "If you don't see the review form, you don't yet have a completed appointment there — the studio/artist needs to mark your appointment \"Completed\" first.",
    ],
    relatedArticleIds: ["client-book-appointment"],
  },
  {
    id: "client-my-studios",
    roles: [Client],
    title: "Switch between studios you're a client at",
    route: "/my-studios",
    keywords: ["multiple studios", "switch studio", "leave studio", "active studio"],
    summary: "Lists every studio you've booked with, shows which one is currently active, and lets you switch between them or leave one.",
    steps: [
      "Browse your list of studios, each showing its name, city, and whether it's your current \"Active\" studio.",
      "Click \"Switch\" on a studio to make it your active studio.",
      "Click the \"⋮\" menu on a studio to view its public profile, manage notification settings, or leave the studio.",
      "Click \"Discover\" (top right) to find and join a new studio.",
    ],
    tips: ["Leaving a studio doesn't delete your history — your appointment records are kept and you can rejoin any time."],
  },
  {
    id: "client-designs",
    roles: [Client],
    title: "View your tattoo designs",
    route: "/designs",
    keywords: ["design drafts", "artwork", "review design"],
    summary: "Shows the tattoo design drafts your artist has uploaded for you to review.",
    steps: [
      "Use the search box to filter designs by title (only shown once you have designs).",
      "Browse your design list — designs waiting on your feedback (\"Changes Requested\") are shown first.",
      "Click a design to open it and review its images.",
    ],
    tips: ["If the list is empty, your artist just hasn't uploaded anything yet — you don't need to do anything."],
    relatedArticleIds: ["client-design-approve"],
  },
  {
    id: "client-design-approve",
    roles: [Client],
    title: "Approve a design or request changes",
    route: "/designs",
    keywords: ["approve", "request changes", "reject design", "design revision"],
    summary: "Look at the artwork your artist uploaded and tell them whether it's ready or needs changes.",
    steps: [
      "Open a design and review each version (revision) shown, including its image.",
      "If a banner says your artist is waiting for feedback, review the latest version.",
      "Click \"Approve\" to accept a version, or \"Request Changes\" to ask for edits.",
      "If requesting changes, optionally describe what to change, then click \"Submit\".",
    ],
    tips: ["Only versions that aren't already approved show the Approve / Request Changes buttons."],
    relatedArticleIds: ["client-designs"],
  },
  {
    id: "client-intake-submit",
    roles: [Client],
    title: "Fill out an intake form",
    route: "/forms/intake/new",
    keywords: ["medical history", "health form", "allergies"],
    summary: "Send your artist your medical history and any health details before your session.",
    steps: [
      "Fill in the \"Medical history & notes\" box (allergies, skin conditions, medications, etc.) — at least 10 characters.",
      "Optionally link the form to one of your upcoming appointments.",
      "Optionally paste a link to an attachment (photo or document).",
      "Click \"Submit Intake Form\".",
    ],
    relatedArticleIds: ["client-intake-list"],
  },
  {
    id: "client-intake-list",
    roles: [Client],
    title: "Find your submitted intake forms",
    route: "/forms/intake",
    keywords: ["intake history", "draft form", "submitted"],
    summary: "Lists all the intake forms you've submitted to the studio, showing which are done and which are still drafts.",
    steps: [
      "Browse your list of intake forms — each shows a headline, date, and \"Submitted\" or \"Draft\" badge.",
      "Click \"Submit intake form\" (top right) to fill out a new one.",
      "Click any form in the list to open its details.",
    ],
    relatedArticleIds: ["client-intake-submit"],
  },
  {
    id: "client-consent-sign",
    roles: [Client],
    title: "Sign a consent form",
    route: "/forms/consent/new",
    keywords: ["digital signature", "sign consent", "agreement"],
    summary: "Digitally sign the consent agreement for an upcoming appointment before your tattoo session. The full consent text is shown on the page so you can read exactly what you're agreeing to before you sign.",
    steps: [
      "Read the consent agreement shown at the top of the page in full.",
      "Select the appointment you're signing consent for from the dropdown.",
      "Type your full legal name in the \"Digital signature\" box to sign.",
      "Click \"Sign Consent Form\".",
    ],
    warnings: ["You can only sign one consent form per appointment — a PDF copy is generated and attached automatically once you sign.", "The exact wording you agreed to is saved with your signature, so a past consent always shows what you actually agreed to even if the studio later updates its consent text."],
    relatedArticleIds: ["client-consent-list"],
  },
  {
    id: "client-consent-list",
    roles: [Client],
    title: "Find your signed consent forms",
    route: "/forms/consent",
    keywords: ["consent history", "signed", "pending consent"],
    summary: "Lists the consent forms tied to your appointments and whether each one has been signed yet.",
    steps: [
      "Browse the list — each row shows the appointment and a \"Signed\" or \"Pending\" badge with the date.",
      "Click \"Sign consent form\" (top right) to sign a new one.",
      "Click any row to view that form's details, including the exact consent text you agreed to at the time you signed.",
    ],
    relatedArticleIds: ["client-consent-sign"],
  },
  {
    id: "client-profile",
    roles: [Client],
    title: "Update your profile and body map",
    route: "/clients/me",
    keywords: ["body map", "tattoo history", "sharing", "contact info"],
    summary: "Your personal profile — contact details, where on your body you have or want tattoos, your past tattoo history, and whether other studios can see your profile.",
    steps: [
      "On the \"Profile\" tab, view your email and phone, click \"Edit\" on the Body Map to mark locations, then \"Save\".",
      "Switch to the \"Tattoo History\" tab to see your completed tattoos with photos and descriptions.",
      "Switch to the \"Sharing\" tab to turn on or off letting other studios reuse your profile information.",
    ],
    relatedArticleIds: ["client-delete-account"],
  },
  {
    id: "client-delete-account",
    roles: [Client],
    title: "Delete my account",
    route: "/clients/me",
    keywords: ["delete account", "erase data", "right to erasure", "gdpr", "remove my data"],
    summary: "Permanently delete your account and personal data (profile, body map, and consent records) yourself — your right to erasure.",
    steps: [
      "Open your profile at Profile, then the \"Sharing\" tab.",
      "In the \"Delete my account\" section, click \"Delete my account\".",
      "Read the warning, type DELETE to confirm, and click \"Delete my account\" in the dialog.",
    ],
    warnings: [
      "You're signed out immediately and can't log back in. Your data is then permanently deleted after a 30-day grace period, after which it's unrecoverable. It cannot be undone.",
      "You only ever delete your own account — it can never affect anyone else's data.",
    ],
    relatedArticleIds: ["client-profile"],
  },
  {
    id: "client-deposit-pay",
    roles: [Client],
    title: "Pay a deposit (card or cash)",
    route: "/pay/:paymentId",
    keywords: ["pay deposit", "checkout", "card payment"],
    summary: "Securely authorize a deposit payment by card for your appointment.",
    steps: [
      "Review the deposit amount shown.",
      "Enter your card details in the payment box.",
      "Click \"Authorise deposit\".",
    ],
    tips: ["Your card isn't charged immediately — it's authorised, and the studio captures the payment closer to your appointment. Payment is by card, or by cash arranged with the studio."],
  },
  {
    id: "client-verify-email",
    roles: [Client],
    title: "Verify your email address",
    route: "/verify-email",
    keywords: ["email verification", "confirm email"],
    summary: "Automatically confirms your email address when you click the verification link sent to your inbox.",
    steps: [
      "Click the verification link in your email, which opens this page.",
      "Wait while the app confirms your email automatically.",
      "If successful, click \"Sign in\" to continue; if it fails, go back to login and request a new link.",
    ],
    warnings: ["If the link has expired or is invalid, verification fails and you must request a new email — the old link cannot be reused."],
  },
  {
    id: "client-change-password",
    roles: [Client, Artist, Owner, Issuer],
    title: "Change your password",
    route: "/account/change-password",
    keywords: ["password", "account security"],
    summary: "Update your account password.",
    steps: [
      "Enter your current password.",
      "Enter a new password (at least 8 characters, with an uppercase letter and a number, different from your current one).",
      "Re-enter the new password to confirm.",
      "Click \"Change password\".",
    ],
    relatedArticleIds: ["client-change-email"],
  },
  {
    id: "client-change-email",
    roles: [Client, Artist, Owner, Issuer],
    title: "Change your email address",
    route: "/account/change-email",
    keywords: ["email", "change email", "account security", "sign-in email"],
    summary: "Switch the email address you use to sign in.",
    steps: [
      "Enter your current password.",
      "Enter your new email address.",
      "Click \"Send confirmation link\".",
      "Open the confirmation email sent to your NEW address and click the link — your email doesn't change until you confirm it.",
    ],
    tips: [
      "Your current email stays active until you confirm the new one, so you won't be locked out mid-change.",
      "A notice is sent to your old email when the change completes, in case it wasn't you.",
    ],
    relatedArticleIds: ["client-change-password"],
  },
  {
    id: "client-messaging",
    roles: [Client],
    title: "Message your artist or the studio",
    route: "/messages",
    keywords: ["messages", "chat", "message artist", "contact studio", "inbox", "text artist"],
    summary: "Send a real-time message to your assigned or booked artist, or to the studio owner, without leaving the app.",
    steps: [
      "Open Messages from the menu.",
      "Click \"New message\" and pick a contact — only your assigned or booked artist and the studio owner are available to message.",
      "Or continue an existing thread from the conversation list.",
      "Type your message and press Enter (or click Send).",
    ],
    tips: [
      "You can only start a thread with an artist you've had an appointment with or who's assigned to you — you can always reach the studio owner.",
      "If the recipient is offline, they get a one-time email so a burst of messages doesn't flood their inbox.",
    ],
    relatedArticleIds: ["client-book-appointment"],
  },

  // ── Artist ──────────────────────────────────────────────────────────────
  {
    id: "artist-schedule",
    roles: [Artist],
    title: "View and manage your schedule",
    route: "/schedule",
    keywords: ["calendar", "weekly schedule", "appointments"],
    summary: "Shows your appointments for one week at a time, organized by day, so you can see your schedule at a glance.",
    steps: [
      "Open Schedule from the menu.",
      "Use the left/right arrows to move to the previous or next week.",
      "Click \"Today\" to jump back to the current week.",
      "Click any appointment card to open its full details.",
    ],
    tips: ["Days with no appointments show \"No appointments\"; the current day is highlighted with a \"Today\" badge."],
  },
  {
    id: "artist-appointment-detail",
    roles: [Artist],
    title: "Open an appointment's details",
    route: "/schedule",
    keywords: ["confirm", "reschedule", "cancel", "no-show", "complete appointment"],
    summary: "Shows the full details of a single appointment — client, date/time, duration, status, and deposit — plus actions to move it forward.",
    steps: [
      "Review the client, date/time, duration, status, and deposit info.",
      "Click \"Message [client name]\" to start or continue a chat thread with the client, if they have a linked login.",
      "Click \"Add to Calendar\" to download an .ics file for the appointment.",
      "Click \"Confirm appointment\" or \"Mark as complete\" to advance its status.",
      "Click \"Reschedule\" to pick a new date/time.",
      "Click \"Mark no-show\" if the client didn't attend, or \"Cancel appointment\" and confirm if it needs to be cancelled.",
    ],
    tips: ["The client's name is a link straight to their client profile."],
    warnings: ["Cancelling an appointment cannot be undone."],
    relatedArticleIds: ["artist-send-manual-reminder", "artist-messaging"],
  },
  {
    id: "artist-send-manual-reminder",
    roles: [Artist, Owner],
    title: "Send a manual reminder",
    route: "/schedule",
    keywords: ["reminder", "sms", "text message", "quick reminder", "send reminder", "notify client"],
    summary: "Send a one-off SMS reminder — right now or scheduled for later — separate from the automatic 48h/24h appointment reminders the studio already sends.",
    steps: [
      "Click \"Send Reminder\" on an appointment's detail page or a client's profile page — the recipient's name and phone number are filled in automatically.",
      "For someone with no appointment or client record yet, use the \"Quick Reminder\" button (message icon) in the Schedule page's toolbar and type in a name and phone number instead.",
      "Optionally write a custom message, or leave it blank to send the studio's default reminder text.",
      "Toggle \"Schedule for later\" and pick a date/time, or leave it off to send immediately.",
      "Click \"Send now\" or \"Schedule reminder\".",
      "Reopen the dialog to see the send history and cancel any reminder that's still Scheduled.",
    ],
    tips: [
      "A Quick Reminder sent to a typed-in name and phone number does not create a client record — it stays a one-off text.",
      "Owners can send a reminder on behalf of any artist from that appointment's or client's page.",
    ],
    warnings: ["There's a daily limit on manual reminders per artist — if you hit it, wait until the next day or contact support."],
    relatedArticleIds: ["artist-appointment-detail", "artist-client-detail", "artist-schedule"],
  },
  {
    id: "artist-clients",
    roles: [Artist],
    title: "Find a client you're working with",
    route: "/clients",
    keywords: ["client search", "client list"],
    summary: "A searchable list of all clients in your studio.",
    steps: [
      "Open Clients from the menu.",
      "Type a name or email in the search box to filter the list.",
      "Click \"New Client\" to add a client.",
      "Click any row (or its \"View\" button) to open that client's profile.",
    ],
  },
  {
    id: "artist-client-detail",
    roles: [Artist],
    title: "View a client's profile and tattoo history",
    route: "/clients",
    keywords: ["client profile", "medical notes", "cross-studio"],
    summary: "A client's full profile — contact info, health details, body map, forms, and appointment history — all in one place. The artist assigned to the client is shown near the top (read-only for this role — only owners can change it).",
    steps: [
      "Open a client from the Clients list.",
      "Click \"Edit Profile\" (or \"Add Profile\" if none exists yet) to enter date of birth, allergies, and medical notes, then \"Save Profile\".",
      "Switch between the Profile, Tattoo History, Forms, and Appointments tabs.",
      "On the Profile tab, click \"Edit\" next to Body Map to mark tattoo locations, then \"Save\".",
      "In the Forms tab, click an intake or consent form entry to open its full detail.",
    ],
    tips: ["A \"Cross-Studio\" tab appears automatically if the client has shared tattoo history from other studios on the app."],
    relatedArticleIds: ["artist-send-manual-reminder"],
  },
  {
    id: "artist-designs",
    roles: [Artist],
    title: "View designs assigned to you",
    route: "/designs",
    keywords: ["design projects", "changes requested"],
    summary: "Your list of tattoo design projects, showing which ones are waiting on your next move.",
    steps: [
      "Open Designs from the menu.",
      "Use the search box to filter by design title.",
      "Designs marked \"Changes Requested\" are automatically pulled to the top since they need your attention.",
      "Click a design card to open it and see its revisions, or click \"New Design\" to start a new one.",
    ],
    relatedArticleIds: ["artist-create-design", "artist-upload-revision"],
  },
  {
    id: "artist-create-design",
    roles: [Artist],
    title: "Create a new design for a client",
    route: "/designs/new",
    keywords: ["new design", "start design"],
    summary: "Start a new tattoo design project for a client so you can upload artwork for their approval.",
    steps: [
      "Open Designs and click \"New Design\".",
      "Select the Client this design is for.",
      "Select the Artist assigned to it.",
      "Enter a Title, and optionally a Description (style, placement, concept).",
      "Click \"Create Design\".",
    ],
    relatedArticleIds: ["artist-upload-revision"],
  },
  {
    id: "artist-upload-revision",
    roles: [Artist],
    title: "Upload a revised design",
    route: "/designs",
    keywords: ["upload artwork", "revision", "new version"],
    summary: "Upload a new version of artwork to an existing design for the client to review.",
    steps: [
      "From a design's page, click \"Upload Revision\".",
      "Click the upload area and choose an image file (JPEG, PNG, or WebP only).",
      "Optionally add notes describing what changed in this revision.",
      "Click \"Upload Revision\" to submit it.",
    ],
    tips: ["The button label shows progress (\"Getting upload URL…\", \"Uploading file…\", \"Saving revision…\") while it uploads."],
  },
  {
    id: "artist-share-design",
    roles: [Artist, Owner],
    title: "Share a design link with a client",
    keywords: ["share link", "public link", "revoke link"],
    summary: "Generate a link so someone without an app account can view a specific design revision.",
    steps: [
      "Open a design and find the revision you want to share.",
      "Click the \"Share\" button on that revision.",
      "Once the link generates, click the copy icon to copy it and send it to whoever needs to view the design.",
      "Click \"Revoke link\" if you want to disable it early.",
    ],
    warnings: ["The share link expires automatically after 30 days; revoking it also cannot be undone — you'd need to generate a new link."],
  },
  {
    id: "artist-intake-view",
    roles: [Artist],
    title: "Review a client's intake form",
    route: "/forms/intake",
    keywords: ["review medical history", "health flags"],
    summary: "Review a client's medical/health intake information that they filled out before their appointment.",
    steps: [
      "Open the client's profile and go to the Forms tab, or open Intake Forms from the menu.",
      "Click the intake form you want to review.",
      "Check the \"Submitted\" or \"Draft\" status at the top.",
      "Review the medical history section — personal info, health flags (allergies, blood conditions, etc.), and any attached file.",
    ],
    tips: ["A form still shows as \"Draft\" if the client hasn't submitted it yet."],
  },
  {
    id: "artist-consent-view",
    roles: [Artist],
    title: "Review a client's signed consent form",
    route: "/forms/consent",
    keywords: ["review signature", "consent document"],
    summary: "Review a client's signed consent form for an appointment, including their signature and any attached document.",
    steps: [
      "Open the client's profile and go to the Forms tab, or open Consent Forms from the menu.",
      "Click the consent form you want to review.",
      "Check the \"Signed\" or \"Pending\" status, client, and linked appointment.",
      "View the digital signature and, if attached, open or download the consent document.",
      "The \"Consent agreement (as signed)\" section shows the exact text the client agreed to at the time — the stored snapshot, not the studio's current wording — so a past consent is always an accurate record.",
    ],
  },
  {
    id: "artist-notifications",
    roles: [Artist],
    title: "Check your notifications",
    keywords: ["bell icon", "alerts", "unread"],
    summary: "The bell icon in the header shows your recent alerts (like new bookings or form submissions) and how many are unread.",
    steps: [
      "Click the bell icon in the top header.",
      "Browse the most recent notifications in the dropdown.",
      "Click a notification to see its full details.",
      "Click \"View all\" to see your complete notification history.",
    ],
    tips: ["Opening the bell automatically clears the unread count badge."],
  },
  {
    id: "artist-messaging",
    roles: [Artist],
    title: "Message a client or the studio owner",
    route: "/messages",
    keywords: ["messages", "chat", "message client", "contact owner", "inbox", "text client"],
    summary: "Send a real-time message to a client you have an appointment with or who's assigned to you, or to the studio owner.",
    steps: [
      "Open Messages from the menu, or click \"Message [client name]\" from an appointment's detail page.",
      "Click \"New message\" and pick a client or the studio owner.",
      "Or continue an existing thread from the conversation list.",
      "Reply in real time — new messages arrive without reloading the page.",
    ],
    tips: [
      "You can only message clients you have an appointment with or who are assigned to you — you can always reach the studio owner.",
      "If the recipient is offline, they get a one-time email so a burst of messages doesn't flood their inbox.",
    ],
    relatedArticleIds: ["artist-schedule"],
  },

  // ── Owner ───────────────────────────────────────────────────────────────
  {
    id: "owner-dashboard",
    roles: [Owner],
    title: "Understand your dashboard",
    route: "/dashboard",
    keywords: ["home screen", "overview", "stats"],
    summary: "Your studio's home screen — a snapshot of today's and this week's appointments, deposits still owed, and any cash payments waiting to be collected.",
    steps: [
      "Open Dashboard from the menu.",
      "Check the banner at the top if your subscription needs attention (trial ending, payment failed, etc.) and click its button to fix it.",
      "Review the stat boxes — Today's appointments, This Week's appointments, and Deposits Due.",
      "Scroll to \"Today\" to see today's bookings, or click \"View schedule\" for the full calendar.",
      "If a client owes cash, they appear under \"Awaiting Cash\" — click the confirm button once you've physically received the money.",
    ],
    tips: ["The \"+ Book Appointment\" button in the top right takes you straight to the Schedule to add a new appointment."],
  },
  {
    id: "owner-artists-add",
    roles: [Owner],
    title: "Add an artist to your studio",
    route: "/artists/new",
    keywords: ["new artist", "hire artist", "hourly rate", "invite", "set password", "resend invite"],
    summary: "Add a new tattoo artist to your studio.",
    steps: [
      "Go to Artists and click \"New Artist\".",
      "Enter the artist's first and last name and email address.",
      "Optionally list their specializations (e.g. Traditional, Realism).",
      "Optionally set an hourly rate — used to calculate percentage-based deposits.",
      "Click \"Create Artist\".",
    ],
    tips: [
      "The hourly rate only matters if you use percentage-based deposit rules for this artist.",
      "You don't set a password for the artist. They get an automatic email with a link to set their own password — it expires after 1 hour.",
      "If the artist says they never received that email, open their profile and click \"Resend invite\" next to their email address.",
    ],
  },
  {
    id: "owner-artists-list",
    roles: [Owner],
    title: "Manage your artists",
    route: "/artists",
    keywords: ["artist list", "edit artist", "delete artist"],
    summary: "Lists every artist working at your studio, with tools to search, filter, edit, or remove them.",
    steps: [
      "Go to Artists to see the full list.",
      "Use the search box to find an artist by name or email, or click a specialization pill to filter.",
      "Click \"Edit\" on a row to open that artist's profile, or \"New Artist\" to add one.",
      "To remove an artist, click \"Delete\", then \"Confirm\".",
    ],
    tips: [
      "If you also tattoo, look for \"Enable my artist profile\" near the top of this page.",
    ],
    warnings: ["Deleting an artist cannot be undone from this screen."],
    relatedArticleIds: ["owner-become-artist"],
  },
  {
    id: "owner-become-artist",
    roles: [Owner],
    title: "Enable your own artist profile",
    route: "/artists",
    keywords: ["owner artist", "I also tattoo", "myself as artist", "owner-operator", "dual role", "become an artist"],
    summary: "If you also tattoo, add yourself as a bookable artist without creating a second account.",
    steps: [
      "Go to Artists.",
      "Click \"Enable my artist profile\" in the banner near the top of the list.",
      "Enter your first and last name, and optionally your specializations and hourly rate.",
      "Click \"Enable my artist profile\".",
    ],
    tips: [
      "This uses your existing owner login — no new email, password, or invite email.",
      "Once enabled, you'll get a \"My Portfolio\" shortcut in your menu, and you'll be selectable when booking or scheduling appointments, just like any other artist.",
      "This counts as one artist seat against your plan's usage, the same as inviting any other artist.",
    ],
    relatedArticleIds: ["owner-artists-list", "owner-solo-studio"],
  },
  {
    id: "owner-solo-studio",
    roles: [Owner],
    title: "Understand your solo studio and the Free plan",
    route: "/dashboard",
    keywords: ["solo", "independent artist", "solo studio", "free plan", "no NIPT", "no business registration", "sign up as artist"],
    summary: "If you registered as an independent artist rather than a full studio, here's what \"solo\" means and how the Free plan works.",
    steps: [
      "If you signed up from the registration page's \"I'm an independent artist\" option, TattooOS auto-created a studio for you behind the scenes — you don't need to register a business first.",
      "Your studio starts on the Free plan (1 artist seat, 15 appointments/month, 50 notifications/month, 1 GB storage) at no cost, active immediately, no trial to expire.",
      "A business tax ID (NIPT) is entirely optional for a solo studio — even once you start taking card or cash payments. You can add one later from Studio Settings if you ever formalize a business, but nothing requires it.",
      "Finish your own artist profile (see \"Enable your own artist profile\") so you're bookable — this can happen before or after your studio has a real address.",
    ],
    tips: [
      "\"Solo\" is just a label on your studio (Studio.IsSolo) — it doesn't restrict anything you can do, it only reflects that you started without a formal studio.",
      "The label goes away automatically the moment you upgrade off the Free plan — see \"Grow beyond one artist\".",
    ],
    relatedArticleIds: ["owner-publish-studio", "owner-solo-upgrade", "owner-become-artist"],
  },
  {
    id: "owner-publish-studio",
    roles: [Owner],
    title: "Publish your studio on the Map and in Discover",
    route: "/studios/me",
    keywords: ["publish", "unpublished", "not on map", "studio map", "discover", "isPublished", "visibility", "location"],
    summary: "A solo studio starts hidden from the Studio Map and Discover until it has a real city and location saved — here's how to fix that.",
    steps: [
      "Go to Studio Settings.",
      "Fill in your real City and pick a location on the map (not the (0, 0) placeholder).",
      "Save — your studio is published automatically the moment a real city and location are on file. There's no separate \"Publish\" button.",
    ],
    tips: [
      "Until published, your studio won't appear on the Studio Map, the /discover Studios tab, or your public studio page — but your own artist page stays public and bookable the entire time, so clients who already have your link can still book you.",
      "A banner reappears each time you log in, reminding you to finish this, until it's actually resolved — dismissing it only hides it for the current browser session.",
      "This is a one-way flip — once published, a studio never goes back to unpublished through this flow.",
    ],
    relatedArticleIds: ["owner-solo-studio", "owner-studio-profile"],
  },
  {
    id: "owner-solo-upgrade",
    roles: [Owner],
    title: "Grow beyond one artist",
    route: "/billing",
    keywords: ["invite second artist", "quota", "max artists", "upgrade plan", "one artist limit"],
    summary: "The Free plan allows exactly one artist seat — here's what happens when you try to add a second, and how to unlock more.",
    steps: [
      "Try to invite a second artist from the Artists page — on the Free plan, this is blocked automatically with a message explaining you're at your plan's limit.",
      "Go to Billing and choose a paid plan to raise (or remove) the artist-seat limit.",
      "Invite your second artist — no other setup needed.",
    ],
    tips: [
      "Upgrading off the Free plan also quietly stops describing your studio as \"solo\" — this is cosmetic only and doesn't change what you can already do.",
      "Your studio's discoverability (published or not) is unaffected by which plan you're on.",
    ],
    relatedArticleIds: ["owner-solo-studio", "owner-billing", "owner-artists-add"],
  },
  {
    id: "owner-invite-solo-artist",
    roles: [Owner],
    title: "Invite an independent artist to join your studio",
    route: "/artists/new",
    keywords: ["invite existing account", "already belongs to an existing account", "send a request to join", "recruit solo artist"],
    summary: "If the artist you're trying to invite already runs their own solo studio, send them a request to join yours instead of a dead-end error.",
    steps: [
      "On the New Artist form, enter the artist's details as usual and submit.",
      "If that email already belongs to an independent artist's own solo studio, you'll see \"Send a request to join instead\" — click it.",
      "The artist gets notified and can accept or decline the next time they sign in. You'll see nothing further from your side until they respond.",
    ],
    tips: [
      "This only works for an email that belongs to another solo studio's owner account — any other existing account (a different studio's artist, client, etc.) still can't be invited this way.",
      "Accepting closes the artist's old solo studio permanently for them — see \"Accept or decline a studio-join invite\" for what that means for them.",
    ],
    relatedArticleIds: ["owner-artists-add", "owner-accept-join-invite"],
  },
  {
    id: "owner-accept-join-invite",
    roles: [Owner, Artist],
    title: "Accept or decline a studio-join invite",
    route: "/dashboard",
    keywords: ["join invite", "studio invite", "accept invite", "decline invite", "dissolve solo studio", "join another studio"],
    summary: "If another studio invites your independent artist account to join them, here's what accepting or declining actually does.",
    steps: [
      "Look for the small mail icon with a badge count near the notification bell — it only appears when you have a pending invite.",
      "Click it to see which studio invited you, then \"Accept\" or \"Decline\".",
      "Accepting shows a confirmation dialog first — read it, since this can't be undone from within the invite.",
      "After accepting, you're signed back in automatically as an artist at the new studio.",
    ],
    tips: [
      "Accepting permanently closes your current solo studio: you stop being its owner and lose access to it, but none of its data (appointments, clients, portfolio, payments) is deleted.",
      "Declining has no side effects — your solo studio and account are completely unaffected, and the inviting studio can send a new invite later if they want to.",
      "This only works if you're still the owner of an active solo studio when you accept — if that's changed since the invite was sent, you'll see an error instead.",
    ],
    relatedArticleIds: ["owner-invite-solo-artist", "owner-solo-studio"],
  },
  {
    id: "owner-artist-portfolio",
    roles: [Owner, Artist],
    title: "Add portfolio images and tag their category and style",
    route: "/artists",
    keywords: [
      "portfolio", "upload image", "tattoo style", "style tag", "discover filter",
      "no portfolio work", "keyword search",
      "fresh tattoo", "healed tattoo", "design", "portfolio category",
    ],
    summary: "Upload work to an artist's portfolio as a fresh tattoo, healed tattoo, or design, and tag each image with a tattoo style — both show up in the public Discover page's filters.",
    steps: [
      "Open an artist's profile and click the \"Portfolio\" tab.",
      "Click \"Add image\" and choose Fresh Tattoo, Healed Tattoo, or Design — this uploads the photo and tags its category in one step.",
      "For each image, use the category dropdown to relabel it later if needed, and the style dropdown to pick a tattoo style (e.g. Traditional, Realism, Blackwork).",
      "Click either dropdown again at any time to change or clear an image's category or style.",
    ],
    tips: [
      "The Discover page's category tabs (All / Fresh Tattoos / Healed Tattoos / Designs) and style filter chips only match an image's own tags — they combine, so a client can filter to \"Healed Tattoos\" and \"Blackwork\" at once.",
      "An image left uncategorized or without a style still shows in the artist's portfolio, but it won't appear when a client filters Discover by that category or style. The separate keyword search box (\"Search styles, artists…\") also matches an artist's name and their \"Specializations\" text, so a well-filled-in Specializations field helps your work surface there even for untagged images.",
    ],
    relatedArticleIds: ["owner-artists-list"],
  },
  {
    id: "owner-clients-add",
    roles: [Owner],
    title: "Add a client manually",
    route: "/clients/new",
    keywords: ["new client", "walk-in client", "assign artist", "preferred artist"],
    summary: "Add a new client record to your studio.",
    steps: [
      "Go to Clients and click \"New Client\".",
      "Enter the client's first and last name and email address.",
      "Select the Artist this client belongs to. (If you're an artist adding your own client, this step doesn't apply — it's assigned to you automatically.)",
      "Optionally enter a phone number.",
      "Click \"Create Client\".",
    ],
  },
  {
    id: "owner-clients-list",
    roles: [Owner],
    title: "Manage your clients",
    route: "/clients",
    keywords: ["client list", "client search"],
    summary: "Lists all clients in your studio so you can search and open their profiles.",
    steps: [
      "Go to Clients to see the full list.",
      "Use the search box to find a client by name or email.",
      "Use the Artist filter to narrow the list to one artist's clients, or \"Unassigned\" for clients with no artist yet.",
      "Click \"View\" on any row (or click the row) to open that client's profile.",
      "Click \"New Client\" to add a new one.",
    ],
  },
  {
    id: "owner-clients-reassign-artist",
    roles: [Owner],
    title: "Reassign a client to a different artist",
    route: "/clients",
    keywords: ["reassign artist", "change artist", "unassign client"],
    summary: "Change which artist a client belongs to, or unassign them, from the client's profile.",
    steps: [
      "Open the client's profile from the Clients list.",
      "Click the artist name shown near the top of the profile to open the dropdown.",
      "Choose a different artist, or choose \"Unassigned\".",
      "The change saves immediately — no separate save button.",
    ],
  },
  {
    id: "owner-designs",
    roles: [Owner],
    title: "Review and manage all studio designs",
    route: "/designs",
    keywords: ["all designs", "design tracking"],
    summary: "Shows every tattoo design uploaded across your studio, so you can track which ones are approved, pending, or need changes.",
    steps: [
      "Go to Designs to see all designs.",
      "Designs the artist needs to revise (\"Changes Requested\") are automatically shown at the top.",
      "Use the search box to find a design by title.",
      "Click a design card to open its details, or \"New Design\" to upload one.",
    ],
  },
  {
    id: "owner-deposit-rules",
    roles: [Owner],
    title: "Set up deposit rules",
    route: "/deposit-rules",
    keywords: ["deposit percentage", "fixed deposit"],
    summary: "Deposit rules define how much clients must pay upfront to secure a booking — either a fixed amount or a percentage.",
    steps: [
      "Go to Deposit Rules to see all your rules.",
      "Click \"New Rule\" to create one, or click an existing rule to view/edit it.",
    ],
    tips: ["If you haven't created any rules yet, new appointments won't have an automatic deposit amount calculated."],
    relatedArticleIds: ["owner-deposit-rule-create"],
  },
  {
    id: "owner-deposit-rule-create",
    roles: [Owner],
    title: "Create a new deposit rule",
    route: "/deposit-rules/new",
    keywords: ["new deposit rule", "percentage deposit", "cancellation policy", "notice window", "late cancellation refund"],
    summary: "Create a new deposit rule that determines how much of a deposit clients pay when booking, and your studio's cancellation policy.",
    steps: [
      "Go to Deposit Rules and click \"New Rule\".",
      "Enter a name for the rule (e.g. \"Standard Deposit\").",
      "Choose \"Fixed amount\" (a set euro amount) or \"Percentage\" (a % of the session cost).",
      "Enter the amount or percentage.",
      "Optionally set a \"Cancellation notice window\" — how many hours' notice a client must give to self-cancel without forfeiting their deposit. Leave blank to use the 48-hour platform default.",
      "Optionally set \"Refund if cancelled late\" — the percentage of the deposit refunded if a client cancels within that window. 0% (the default) forfeits the deposit entirely.",
      "Leave \"Active\" checked if you want the rule to apply immediately, then click \"Create Rule\".",
    ],
    tips: [
      "Percentage rules must be between 0.01% and 100%.",
      "The cancellation notice window also gates client self-reschedule, not just self-cancel.",
    ],
  },
  {
    id: "owner-schedule",
    roles: [Owner],
    title: "View the studio-wide schedule",
    route: "/schedule",
    keywords: ["studio calendar", "all appointments"],
    summary: "Shows every appointment booked across your whole studio, organized by week and day.",
    steps: [
      "Go to Schedule.",
      "Use the left/right arrows to move between weeks, or click \"Today\" to jump back to the current week.",
      "Click any appointment card to see more details or take action on it.",
      "Appointments waiting on an artist show a \"Needs artist\" badge — open one and assign an artist from its detail page before it can be confirmed.",
    ],
    relatedArticleIds: ["owner-appointments-assign-artist"],
  },
  {
    id: "owner-appointments-assign-artist",
    roles: [Owner],
    title: "Assign an artist to a studio-choice booking",
    route: "/schedule",
    keywords: ["assign artist", "needs artist", "unassigned booking"],
    summary: "Pick which artist does the work for a client who let the studio choose.",
    steps: [
      "Open the appointment from Schedule — look for the \"Needs artist\" badge.",
      "Use the Artist dropdown near the top of the appointment to pick an artist.",
      "The client is emailed once you've assigned one, and the appointment can now be confirmed.",
    ],
  },
  {
    id: "owner-payments",
    roles: [Owner],
    title: "Track deposits and payments",
    route: "/payments",
    keywords: ["payment list", "cash pending", "paid"],
    summary: "Lists every payment recorded in your studio — card and cash — so you can track what's been paid, is pending, or refunded.",
    steps: [
      "Go to Payments to see the list.",
      "Use the search box to find payments by client name, or click a status pill (e.g. Pending, Cash Pending, Paid) to filter.",
      "Click \"New payment\" to record a new one.",
      "Click \"View\" on any row to open its details, or \"Load more\" to see older payments.",
    ],
  },
  {
    id: "owner-payment-create",
    roles: [Owner],
    title: "Create a payment request manually",
    route: "/payments/new",
    keywords: ["new payment", "record payment", "checkout link"],
    summary: "Record a new deposit payment for an appointment, either by card or cash.",
    steps: [
      "Go to Payments and click \"New payment\".",
      "Search and select an appointment that has a pending deposit.",
      "Choose \"Card\" or \"Cash\" as the payment method.",
      "Confirm or adjust the deposit amount.",
      "Click \"Create card payment\" or \"Record cash payment\".",
      "For card payments, copy the checkout link and send it to the client; for cash, it stays pending until you confirm receipt later.",
    ],
    tips: ["If no deposit rule applies to the appointment, you'll need to type in the amount manually."],
  },
  {
    id: "owner-cash-confirm",
    roles: [Owner, Artist],
    title: "Confirm a cash deposit was received",
    keywords: ["cash received", "confirm payment"],
    summary: "Mark a cash deposit as officially received once the client has physically paid.",
    steps: [
      "Open the payment's detail page (from Payments list, or the \"Awaiting Cash\" section on the Dashboard).",
      "Once you've collected the cash from the client, click \"Confirm cash received\".",
      "The payment status updates to Paid.",
    ],
    warnings: ["Only confirm once you have actually received the cash — this action records the payment as collected."],
  },
  {
    id: "owner-studio-profile",
    roles: [Owner],
    title: "Edit your studio profile",
    route: "/studios/me",
    keywords: ["studio settings", "studio name", "address", "description", "nipt", "tax id", "business id"],
    summary: "Edit your studio's public details — name, address, phone, description — and your business tax ID (NIPT), which clients don't see but is used for invoicing and verification.",
    steps: [
      "Go to Studio Settings.",
      "Click \"Edit\" and update your studio name, address/city, phone number, or description.",
      "If you haven't added your NIPT yet, enter it in the Business tax ID field — format is one letter, 8 digits, one letter (e.g. L01234567A). Once saved, this field becomes read-only; contact support to change it.",
      "Click \"Save\" to publish the changes.",
    ],
    tips: [
      "Your NIPT is never shown to clients or on your public booking page — it's for invoicing and business verification only.",
      "To manage your studio's Instagram, TikTok, Facebook, X, and YouTube links, use the \"Social Media\" card further down this page — see \"Verify your studio's or artist's social media accounts\".",
    ],
    relatedArticleIds: ["owner-branding", "owner-embed", "owner-qr-code", "owner-referral", "owner-social-verification"],
  },
  {
    id: "owner-social-verification",
    roles: [Owner, Artist],
    title: "Verify your studio's or artist's social media accounts",
    route: "/studios/me",
    keywords: ["instagram", "tiktok", "facebook", "twitter", "x", "youtube", "verified badge", "social media", "verify account"],
    summary: "Connect or verify Instagram, TikTok, Facebook, X, and YouTube accounts so clients see a green \"Verified\" checkmark next to your handle — proof it's really your account, not something anyone could type into a form.",
    steps: [
      "For a studio: go to Studio Settings and find the \"Social Media\" card. For an artist: open the artist's profile and go to the \"Social\" tab.",
      "For Instagram and TikTok, click \"Connect\" and sign in on the platform's own page — this proves you own the account directly, no typing required.",
      "For Facebook, X, or YouTube (or an Instagram/TikTok account that can't or won't connect), type the handle in the field, then click \"Get verification code\". Add the code shown to that platform's bio, then click \"I've added it — Verify\".",
      "Once verified, a green \"Verified\" badge appears next to the handle everywhere it's shown, including your public page.",
    ],
    tips: [
      "A green check means we've directly confirmed this is the same account, not something anyone else could type in.",
      "Changing a handle after it's verified removes the badge until it's re-verified — the old proof only covered the previous handle.",
      "\"Not available yet\" means that platform isn't connected on this server yet — this is expected for some platforms and isn't something you can fix from Settings.",
      "Disconnecting keeps the handle displayed but removes the Verified badge.",
    ],
    relatedArticleIds: ["owner-studio-profile"],
  },
  {
    id: "owner-branding",
    roles: [Owner],
    title: "Turn off \"Powered by TattooOS\" branding",
    keywords: ["remove branding", "white label"],
    summary: "This toggle controls whether the \"Powered by TattooOS\" credit is shown on your public booking widget.",
    steps: [
      "Go to Studio Settings and scroll to \"Platform branding\".",
      "Switch the toggle to turn \"Powered by TattooOS\" on or off in your booking widget footer.",
    ],
    tips: ["Removing the branding may require upgrading your plan — if your plan doesn't allow it, the toggle will be disabled with an upgrade note."],
  },
  {
    id: "owner-embed",
    roles: [Owner],
    title: "Get your booking widget embed code",
    keywords: ["embed code", "website widget"],
    summary: "Get a ready-made snippet of code to embed your studio's booking widget on your own website.",
    steps: [
      "Go to Studio Settings and scroll to \"Booking widget\".",
      "Click the copy icon to copy the embed code snippet.",
      "Paste it into your website's HTML where you want the booking widget to appear.",
      "Click \"Open preview\" to see what the widget looks like before embedding it.",
    ],
  },
  {
    id: "owner-qr-code",
    roles: [Owner],
    title: "Download your studio's QR code",
    keywords: ["qr code", "print marketing"],
    summary: "Get a scannable QR code that links directly to your studio's booking page, for business cards, storefronts, or social media.",
    steps: [
      "Go to Studio Settings and scroll to \"Marketing QR code\".",
      "Click \"Download PNG\" or \"Download SVG\" to save the QR code image.",
      "Optionally copy the plain link shown above the QR code to share directly.",
    ],
  },
  {
    id: "owner-referral",
    roles: [Owner],
    title: "Get your referral code",
    keywords: ["invite a studio", "referral link", "free month"],
    summary: "Get a unique referral link and code to share with other tattoo studios — when a new studio signs up and subscribes, both of you get a free month.",
    steps: [
      "Go to Studio Settings and scroll to \"Referral programme\".",
      "If you don't have a code yet, click \"Generate referral code\".",
      "Click the copy icon to copy your referral link and share it.",
      "Track studios that used your code and rewards earned in the stats shown below.",
    ],
  },
  {
    id: "owner-notifications",
    roles: [Owner],
    title: "Review sent notifications",
    route: "/notifications",
    keywords: ["email log", "sms log", "delivery status"],
    summary: "A log of every email and SMS notification your studio has sent to clients, showing whether each one was delivered successfully.",
    steps: [
      "Go to Notifications to see the full log.",
      "Use the Channel dropdown to filter by Email or SMS.",
      "Use the From/To date pickers to narrow the log to a date range.",
      "Click any entry to see its full content.",
    ],
  },
  {
    id: "owner-billing",
    roles: [Owner],
    title: "Understand your plan, trial, and billing",
    route: "/billing",
    keywords: ["subscription", "invoices", "plan usage"],
    summary: "Shows your studio's current subscription plan, status, and usage against your plan's limits, plus options to change or manage your billing.",
    steps: [
      "Go to Billing to see your plan, status, and next renewal or trial end date.",
      "Review the \"Plan usage\" card to see how close you are to your plan's limits.",
      "If you're on a paid card-billed plan, click \"Change plan\" or \"Manage billing\".",
      "If a plan change is scheduled, click \"Keep current plan\" to cancel it before it takes effect.",
    ],
    relatedArticleIds: ["owner-subscribe"],
  },
  {
    id: "owner-subscribe",
    roles: [Owner],
    title: "Choose or change your subscription plan",
    route: "/billing/subscribe",
    keywords: ["upgrade plan", "checkout", "monthly yearly"],
    summary: "Choose or change your studio's subscription plan and pay by card.",
    steps: [
      "Go to Billing and click \"Subscribe\" / \"Upgrade\" / \"Change plan\".",
      "Toggle between Monthly and Yearly billing (yearly usually saves money).",
      "Click a plan card to select it.",
      "Click the button at the bottom to continue to checkout, switch plan, or activate the Free plan.",
    ],
    tips: ["If you'd rather pay by cash, contact support using the link at the bottom of the page instead — your trial keeps running until it's set up."],
    warnings: ["Downgrading an existing card-billed plan takes effect only at the end of your current billing period, and you can't select a new plan while a change is already scheduled."],
  },
  {
    id: "owner-reports",
    roles: [Owner],
    title: "Revenue reports",
    route: "/reports",
    keywords: ["revenue", "trend", "per artist", "earnings", "analytics"],
    summary: "See your studio's revenue trend over the last 12 months and a breakdown of revenue by artist.",
    steps: [
      "Go to Reports to see the revenue trend chart, based on paid deposits over the last 12 months.",
      "Hover over a point on the chart to see that month's exact revenue.",
      "Scroll down to \"Revenue by artist\" for a breakdown of the last 30 days, sorted highest first.",
    ],
    tips: ["Only fully paid deposits (card captured or cash confirmed) count toward these figures — pending or refunded ones don't."],
  },
  {
    id: "owner-messaging",
    roles: [Owner],
    title: "Message any artist or client",
    route: "/messages",
    keywords: ["messages", "chat", "message artist", "message client", "inbox"],
    summary: "Send a real-time message to any artist or client at your studio.",
    steps: [
      "Open Messages from the menu, or click \"Message [client name]\" from an appointment's detail page.",
      "Click \"New message\" and pick any artist or client at your studio.",
      "Or continue an existing thread from the conversation list.",
      "Reply in real time — new messages arrive without reloading the page.",
    ],
    tips: ["As the owner, you're the only role with no messaging restrictions — you can start a thread with anyone at your studio."],
  },
  // ── Issuer ──────────────────────────────────────────────────────────────
  {
    id: "issuer-dashboard",
    roles: [Issuer],
    title: "Read the platform dashboard",
    route: "/platform",
    keywords: ["platform overview", "mrr", "kpi"],
    summary: "A snapshot of how the whole platform is doing — how many studios, how much revenue, and which studios need attention.",
    steps: [
      "View the KPI cards for totals (Total Studios, Active Subscriptions, MRR, ARPU).",
      "View the pipeline cards (Trialing, Grace Period, Past Due, Cancelled).",
      "Scroll to the MRR chart.",
      "Check \"At-Risk Studios\" and use \"Extend trial\" inline, or click through to that studio.",
    ],
    tips: ["Clicking most KPI cards jumps straight to a pre-filtered Studios or Subscriptions list."],
  },
  {
    id: "issuer-studios",
    roles: [Issuer],
    title: "Oversee all studios",
    route: "/platform/studios",
    keywords: ["studio list", "manage studios"],
    summary: "The full list of every studio on the platform, where you can search, filter, and manage each one.",
    steps: [
      "Search by studio name or slug, and filter by status or plan.",
      "Browse studios, grouped by status.",
      "Click \"View\" to open a studio's full detail page, or use a row's Extend Trial, Activate, Suspend/Reactivate, or Cancel Subscription buttons directly.",
    ],
    tips: ["Use the copy icon next to a studio's slug to quickly copy it."],
  },
  {
    id: "issuer-studio-detail",
    roles: [Issuer],
    title: "Open a single studio's detail",
    route: "/platform/studios",
    keywords: ["studio detail", "owner info"],
    summary: "A full profile of one studio — its info, owner, usage numbers, referral codes, and all the actions you can take on it.",
    steps: [
      "Review the studio info card (slug, city, registered date, branding setting, plan, subscription status).",
      "Review the Studio Overview card (owner name/email, artist/client/appointment counts).",
      "Generate or manage referral codes for this studio.",
      "Use the Actions panel on the right for Extend Trial, Activate, Suspend/Reactivate, or Cancel Subscription.",
    ],
    tips: ["Click \"View public portfolio\" to open the studio's live public page in a new tab."],
  },
  {
    id: "issuer-suspend-studio",
    roles: [Issuer],
    title: "Suspend or unsuspend a studio",
    keywords: ["suspend", "lock out", "reactivate studio"],
    summary: "Temporarily lock a studio out of the platform without deleting anything, or restore access afterward.",
    steps: [
      "Go to the studio's detail page (or its row in the Studios list).",
      "Click \"Suspend Studio\" (or \"Reactivate Studio\" if already suspended).",
      "Read the confirmation message, then click \"Confirm\".",
    ],
    warnings: ["Suspending a studio immediately hides it from Discover and blocks logins for its owner and all its artists — this takes effect right away, though it can be undone anytime with \"Reactivate Studio\"."],
  },
  {
    id: "issuer-plans",
    roles: [Issuer],
    title: "Manage subscription plans",
    route: "/platform/plans",
    keywords: ["plan catalogue", "pricing"],
    summary: "The catalogue of subscription plans studios can sign up for.",
    steps: [
      "Browse existing plans as cards (price, features, usage limits, number of subscribed studios).",
      "Click \"New plan\" to create one.",
      "Click the pencil icon to edit a plan, or the trash icon to delete it, then confirm.",
    ],
    warnings: ["Deleting a plan is permanent and stops new studios from signing up to it — studios already subscribed keep their subscription unaffected."],
  },
  {
    id: "issuer-plan-edit",
    roles: [Issuer],
    title: "Create or edit a plan",
    route: "/platform/plans/new",
    keywords: ["plan price", "usage limits", "feature flags"],
    summary: "Create a new subscription plan or edit an existing one, including its price and usage limits.",
    steps: [
      "Enter the plan Name and the Yearly discount percentage.",
      "Turn on Monthly price and/or Yearly price, entering the price for each.",
      "Toggle feature flags: Allow branding removal.",
      "Set usage limits (Artists, Appointments/mo, Notifications/mo, Storage, Locations) or check \"Unlimited\".",
      "Click Save.",
    ],
    tips: ["A plan must be either fully free (all prices €0) or fully paid — you can't mix a free interval with a paid one."],
  },
  {
    id: "issuer-subscriptions",
    roles: [Issuer],
    title: "Oversee all subscriptions",
    route: "/platform/subscriptions",
    keywords: ["billing oversight", "subscription status"],
    summary: "A full list of every studio's subscription status across the platform, so you can review and manage billing situations one by one.",
    steps: [
      "Filter by status using the chips at the top (Active, Trialing, Grace Period, Past Due, Cancelled, etc.).",
      "Search by studio name or slug.",
      "Sort by trial end date, period end date, or studio name.",
      "Use each row's Extend Trial, Activate, or Cancel Subscription buttons as needed.",
    ],
  },
  {
    id: "issuer-extend-trial",
    roles: [Issuer],
    title: "Extend a studio's trial",
    keywords: ["grant extension", "more trial days"],
    summary: "Give a studio extra time before their trial (or grace period) runs out, without requiring payment.",
    steps: [
      "Find the studio on the Dashboard, Studios list, Subscriptions list, or its detail page.",
      "Click \"Extend Trial (+7 days)\" (shown as \"Grant Extension\" if the trial already expired).",
      "Enter the number of extra days (defaults to 7, 1–90 allowed).",
      "Click \"Confirm\".",
    ],
  },
  {
    id: "issuer-activate-cash-sub",
    roles: [Issuer],
    title: "Activate a subscription paid by cash",
    keywords: ["cash payment", "manual activation"],
    summary: "Mark a studio's subscription as paid when they paid you outside the app, in cash, instead of by card.",
    steps: [
      "Click \"Activate\" on the studio (Dashboard row, Studios list, Subscriptions list, or detail page).",
      "Select the plan they paid for.",
      "Optionally add a note (e.g. the date cash was received).",
      "Click \"Activate subscription\".",
    ],
    tips: ["Only use this for cash payments collected in person — card payments go through the studio's own checkout automatically."],
  },
  {
    id: "issuer-referrals",
    roles: [Issuer],
    title: "Manage platform referral codes",
    route: "/platform/referrals",
    keywords: ["referral code", "generate code"],
    summary: "Create and manage referral codes that let studios invite other studios to join the platform.",
    steps: [
      "Click \"Generate Code\".",
      "Pick the studio the code is for, and optionally set an expiry date.",
      "Click \"Generate\".",
      "From the list, copy, deactivate, reactivate, or delete existing codes; search or filter by Active/Inactive.",
    ],
    tips: ["Each studio can only have one active code at a time — generating a new one automatically deactivates its old one."],
    warnings: ["Deleting a code with zero redemptions cannot be undone. A code that has already been redeemed can't be deleted at all, only deactivated."],
  },
  {
    id: "issuer-reports",
    roles: [Issuer],
    title: "Read monthly industry reports",
    route: "/platform/reports",
    keywords: ["analytics", "plan usage report"],
    summary: "Platform-wide, anonymized statistics (bookings, trial conversion, revenue growth) plus a live table of how each studio's usage compares to their plan limits.",
    steps: [
      "Browse previously generated monthly reports.",
      "Click \"Download\" to save one, or \"Open\" to view it in a new tab.",
      "Click \"Generate Report\" to trigger a new one immediately (60-second cooldown after each trigger).",
      "Scroll down to the \"Plan usage report\" table to see each studio's usage against their plan's limits.",
    ],
    tips: ["Reports contain no studio names or personal data — they're aggregated platform-wide. New reports also generate automatically on the 1st of every month."],
  },
  {
    id: "issuer-feedback",
    roles: [Issuer],
    title: "Read feedback submitted by owners",
    route: "/platform/feedback",
    keywords: ["bug reports", "feature requests", "inbox"],
    summary: "The inbox where bug reports, feature requests, and general feedback sent in by studio users land for you to review.",
    steps: [
      "Filter by type (Bug Report, Feature Request, General) and/or status (Open, Reviewing, Resolved, Dismissed).",
      "Click a feedback card to expand it and read the full message.",
      "Optionally write an internal note (only visible to you, not the sender).",
      "Click a status button to mark it Open, Reviewing, Resolved, or Dismissed.",
    ],
  },
  {
    id: "issuer-help-insights",
    roles: [Issuer],
    title: "Review Help search insights",
    route: "/platform/help-insights",
    keywords: ["help search analytics", "zero-result queries", "missing documentation"],
    summary: "See what studio users searched for in the in-app Help menu, including which searches returned no results — the clearest signal of missing or confusing documentation.",
    steps: [
      "Open Help Insights from the platform nav.",
      "Review the top queries table to see what users look for most.",
      "Review the zero-result queries table — each of these is a documentation or UX gap worth fixing.",
    ],
    tips: ["Data covers a rolling 30-day window and is aggregated across all studios."],
  },
  {
    id: "issuer-live-traffic",
    roles: [Issuer],
    title: "See who's on the site right now",
    route: "/platform/traffic",
    keywords: ["live traffic", "visitors", "analytics", "site traffic", "geography", "country", "real-time", "map", "ISP", "network"],
    summary: "A real-time view of everyone currently browsing the platform — guests and signed-in users by role — plus a live world map and historical trends by country, network, device, and page.",
    steps: [
      "Open Live Traffic from the platform nav.",
      "The top row shows how many people are on the site right now, split into Guests and each signed-in role.",
      "The live visitor map plots a dot for each current visitor with a resolved location — click a dot for their role, city, and device.",
      "The live table lists each current visitor's role, studio (if applicable), approximate location, device, and current page.",
      "Scroll down for the historical trend chart, top countries, device/browser breakdown, top pages, and top networks (ISP) — use the 7d/30d/90d toggle above the chart to change the time window for all of them at once.",
    ],
    tips: ["Country/city is approximate, resolved from IP address — it can be off by a city or two, especially on mobile networks.", "No visitor is ever identified by name, email, or IP address here — only role, rough location, network, and device.", "A visitor without a resolvable location (private network, GeoIP miss) still appears in the live table but won't show a dot on the map.", "A pulsing 'Live' badge in the header confirms the real-time feed is connected — if it says 'Reconnecting…' or 'Offline,' the numbers on screen may be stale; use the ↻ button next to it to refresh manually."],
    relatedArticleIds: ["issuer-audit-log"],
  },
  {
    id: "issuer-audit-log",
    roles: [Issuer],
    title: "Review the platform audit log",
    route: "/platform/audit-log",
    keywords: ["audit log", "admin actions", "compliance", "who did what"],
    summary: "A searchable, cross-tenant log of every trust-sensitive action taken on the platform — studio suspensions, subscription changes, plan edits, referral code changes, and more.",
    steps: [
      "Open Audit Log from the platform nav.",
      "Filter by action, target type, or a date range.",
      "Each row shows when it happened, what happened, what it targeted, which studio (or \"Platform-wide\" for actions with no single studio target), and the actor's role.",
    ],
    tips: ["Entries never contain names, emails, or free text — only IDs, roles, and structural values, so this log is safe to reference without exposing personal data."],
  },
  {
    id: "owner-audit-log",
    roles: [Owner],
    title: "Recent studio activity",
    route: "/studios/me",
    keywords: ["recent activity", "audit", "who did what"],
    summary: "A read-only list of the most recent trust-sensitive actions taken on your studio (e.g. a client-cancelled appointment), shown on your Studio Settings page.",
    steps: [
      "Go to Studio Settings and scroll to \"Recent studio activity\".",
      "Each entry shows the action and when it happened.",
    ],
  },
  {
    id: "artist-owner-send-feedback",
    roles: [Artist, Owner],
    title: "Send feedback",
    keywords: ["feedback", "bug report", "feature request", "report a bug", "attachment", "screenshot", "video"],
    summary: "Report a bug, request a feature, or share general feedback with the team, with an optional screenshot or short video attached.",
    steps: [
      "Click the feedback icon to open \"Send Feedback\".",
      "Choose a Type (Bug Report, Feature Request, or General), add a Title and Description.",
      "Optionally attach up to 3 screenshots or short video clips under \"Attachments\" — click the box to pick files.",
      "Click \"Send Feedback\".",
    ],
    tips: ["Attachments upload as soon as you pick them — wait for each one to finish before submitting."],
  },
  {
    id: "client-report-artist-studio",
    roles: [Client],
    title: "Report an artist or studio",
    keywords: ["report", "complaint", "abuse", "scam", "unsafe", "harassment", "discrimination", "misconduct", "trust and safety"],
    summary: "File a report about a serious issue with an artist or studio — scam, sexual misconduct, unsafe hygiene practices, harassment, discrimination, or poor service — reviewed by our platform team, not shown publicly.",
    steps: [
      "Go to the studio's page (/s/{slug}) or the artist's page (/artist/{slug}) and scroll below Reviews to \"Report this artist\" / \"Report this studio\".",
      "Pick a category and the appointment your report relates to.",
      "Describe what happened in your own words (minimum 20 characters), and optionally attach up to 3 screenshots or short video clips as evidence.",
      "Click \"Submit Report\".",
    ],
    tips: [
      "Scam, sexual misconduct, unsafe hygiene practices, harassment, and discrimination are escalated immediately to our platform team for review.",
      "You won't see the report again after submitting it — there's no \"my reports\" list — but it has been received and reviewed.",
      "You need a real appointment with the artist/studio to file a report — it doesn't need to be completed, just real.",
    ],
    relatedArticleIds: ["client-leave-review"],
  },
  {
    id: "owner-conduct-reports",
    roles: [Owner],
    title: "Review conduct reports",
    route: "/conduct-reports",
    keywords: ["conduct reports", "trust and safety", "complaint", "misconduct", "escalated"],
    summary: "Reports clients have filed about your studio or your artists — reviewed here, with an open-count badge in the nav.",
    steps: [
      "Open Conduct Reports from the nav.",
      "Click a report card to expand it and read the full description and category.",
      "For a Standard-severity report (poor service, other), set its status to Open, Reviewing, Resolved, or Dismissed.",
      "A High-severity report (scam, sexual misconduct, unsafe hygiene, harassment, discrimination) shows as escalated instead — only Pena e Artë platform staff can close it, though you can still read it in full, including who filed it.",
    ],
    tips: ["High-severity reports are locked to platform-only resolution deliberately — an owner resolving a serious report about their own artist would be a conflict of interest."],
  },
  {
    id: "artist-conduct-reports",
    roles: [Artist],
    title: "See reports filed about you",
    route: "/conduct-reports",
    keywords: ["conduct reports", "reported", "complaint about me"],
    summary: "Reports clients have filed about you specifically — the category, the description, and which appointment it relates to.",
    steps: [
      "Open Reports About Me from the nav.",
      "Click a report card to expand it and read the full description.",
    ],
    tips: ["The reporting client's name, email, and account are never shown to you — only the studio owner and Pena e Artë platform staff can see who filed a report."],
  },
  {
    id: "issuer-conduct-reports",
    roles: [Issuer],
    title: "Resolve conduct reports",
    route: "/platform/conduct-reports",
    keywords: ["conduct reports", "trust and safety", "moderation", "misconduct"],
    summary: "The cross-tenant inbox for every conduct report filed on the platform — filter by category, status, or studio, and resolve any report regardless of severity.",
    steps: [
      "Open Conduct Reports from the platform nav.",
      "Filter by status and/or category.",
      "Click a report card to expand it and read the full description, including the reporter's identity.",
      "Click a status button to mark it Open, Reviewing, Resolved, or Dismissed — issuer status controls are never locked, unlike an owner's on a High-severity report.",
    ],
  },
];

export const FAQ_ITEMS: FaqItem[] = [
  {
    id: "faq-solo-nipt-required",
    roles: [Owner],
    question: "Do I need a business tax ID (NIPT) to sign up as an independent artist?",
    answer: "No. A solo studio never requires a NIPT, even once you start accepting card or cash payments. You can add one later from Studio Settings if you ever formalize a business, but it's always optional for a solo studio.",
    relatedArticleIds: ["owner-solo-studio"],
  },
  {
    id: "faq-solo-join-studio-data",
    roles: [Owner],
    question: "What happens to my appointments, clients, and payments if I join another studio?",
    answer: "Nothing is deleted or moved. Your solo studio is closed and you lose owner access to it, but all its historical data stays exactly where it is. You start fresh as an artist at the new studio.",
    relatedArticleIds: ["owner-accept-join-invite"],
  },
  {
    id: "faq-trial-length",
    roles: [Owner],
    question: "How long is the free trial, and what happens when it ends?",
    answer: "New studios get a 14-day full-featured trial with no credit card required. After the trial ends, you get a 7-day read-only grace period, and if you still haven't subscribed after that, your studio is suspended until you do.",
    relatedArticleIds: ["owner-billing", "owner-subscribe"],
  },
  {
    id: "faq-grace-period",
    roles: [Owner],
    question: "What is the 7-day grace period, and what can I do during it?",
    answer: "The 7-day grace period starts right after your trial ends. During it, you can still view everything in the app, but you can't make changes (no new bookings, no edits) until you subscribe. A banner reminds you the whole time.",
    relatedArticleIds: ["owner-billing"],
  },
  {
    id: "faq-cash-vs-card",
    roles: [Owner, Client],
    question: "What's the difference between paying by card and paying by cash?",
    answer: "Card payments are authorised at booking and the studio captures the payment later. Cash payments are declared by the client at booking, then the studio or artist confirms it in the app once the cash is physically received. There is no PayPal or other payment method.",
    relatedArticleIds: ["client-deposit-pay", "owner-payment-create"],
  },
  {
    id: "faq-cash-confirm-who",
    roles: [Owner, Artist],
    question: "Who has to confirm a cash deposit was received?",
    answer: "Either the owner or the artist on the appointment can confirm a cash deposit once the client has physically paid.",
    relatedArticleIds: ["owner-cash-confirm"],
  },
  {
    id: "faq-deposit-statuses",
    roles: [Owner, Artist, Client],
    question: "What do the different deposit statuses mean?",
    answer: "Pending means the deposit hasn't been paid yet. Paid means it's been received (card captured or cash confirmed). Refunded means it was paid back to the client. Forfeited means the client kept it forfeited per your studio's cancellation terms.",
    relatedArticleIds: ["owner-payments"],
  },
  {
    id: "faq-client-cancel-refund",
    roles: [Client],
    question: "Do I get my deposit back if I cancel my appointment?",
    answer: "It depends on the studio's cancellation policy. Cancel with enough notice (the studio's configured notice window, 48 hours by default) and you get a full refund. Cancel later than that and you may only get a partial refund, or none at all, depending on the studio's settings.",
    relatedArticleIds: ["client-cancel-booking"],
  },
  {
    id: "faq-design-statuses",
    roles: [Client, Artist, Owner],
    question: "What do the different design statuses mean?",
    answer: "Pending means the client hasn't reviewed the latest version yet. Approved means the client accepted it. Changes Requested means the client asked for edits and it's waiting on the artist. Expired means it went unreviewed too long.",
    relatedArticleIds: ["client-design-approve", "artist-designs"],
  },
  {
    id: "faq-appointment-statuses",
    roles: [Client, Artist, Owner],
    question: "What do the different appointment statuses mean?",
    answer: "Pending means the booking request hasn't been confirmed yet. Confirmed means the studio accepted it. Completed means the session happened. Cancelled means it was called off. No-Show means the client didn't attend.",
    relatedArticleIds: ["artist-appointment-detail"],
  },
  {
    id: "faq-multi-studio",
    roles: [Client],
    question: "I go to more than one studio — can I use one account for both?",
    answer: "Yes. Your account can belong to multiple studios at once. Use the My Studios page to switch which studio is currently active, or to leave one you no longer visit.",
    relatedArticleIds: ["client-my-studios"],
  },
  {
    id: "faq-portable-profile",
    roles: [Client],
    question: "Can a new studio see my tattoo history from another studio?",
    answer: "Only if you turn on sharing for your profile. By default your history stays private to each studio. You control this from the Sharing tab on your profile page. When you opt in, other studios can see your tattoo history — your body-map locations, tattoo photos, and descriptions. They can never see your medical notes, allergies, contact details, payment history, or consent forms, and you can turn sharing off again at any time.",
    relatedArticleIds: ["client-profile"],
  },
  {
    id: "faq-branding-removal",
    roles: [Owner],
    question: "Can I remove the \"Powered by TattooOS\" footer?",
    answer: "Yes, from Studio Settings under \"Platform branding\" — though on some plans this may require upgrading first.",
    relatedArticleIds: ["owner-branding"],
  },
  {
    id: "faq-referral-reward",
    roles: [Owner],
    question: "What do I get for referring another studio?",
    answer: "When a studio you referred signs up with your code and becomes a paying subscriber, you both get a free month added to your subscription.",
    relatedArticleIds: ["owner-referral"],
  },
  {
    id: "faq-share-design-expiry",
    roles: [Client, Artist, Owner],
    question: "How long does a shared design link last?",
    answer: "A shared design link expires automatically 30 days after it's created. It can also be revoked earlier by the artist or owner, which can't be undone — a new link would need to be generated.",
    relatedArticleIds: ["artist-share-design"],
  },
  {
    id: "faq-qr-code-use",
    roles: [Owner],
    question: "What is the studio QR code for?",
    answer: "It's a scannable code that links straight to your studio's public booking page — handy for business cards, your storefront, or social media. Download it as a PNG or SVG from Studio Settings.",
    relatedArticleIds: ["owner-qr-code"],
  },
  {
    id: "faq-notification-channels",
    roles: [Client, Artist, Owner],
    question: "How will I be notified about appointments?",
    answer: "By email and, when a phone number is on file, by SMS. Owners can review every notification sent to their clients from the Notifications page.",
    relatedArticleIds: ["owner-notifications"],
  },
  {
    id: "faq-forgot-password",
    roles: [Client, Artist, Owner, Issuer],
    question: "I forgot my password — what do I do?",
    answer: "Click \"Forgot password?\" on the login screen and enter your email. You'll get a reset link — click it to set a new password. Reset links expire 1 hour after they're sent; if yours has expired, the reset page shows a \"Request a new reset link\" button that takes you straight back to the forgot-password form.",
  },
  {
    id: "faq-issuer-suspend-effect",
    roles: [Issuer],
    question: "What happens to a studio immediately after I suspend it?",
    answer: "It's hidden from Discover right away, and its owner and all its artists are immediately blocked from logging in. Nothing is deleted, and you can reverse it anytime with \"Reactivate Studio\".",
    relatedArticleIds: ["issuer-suspend-studio"],
  },
  {
    id: "faq-issuer-cash-subscription",
    roles: [Issuer],
    question: "How do I activate a studio's subscription if they paid by cash?",
    answer: "Open the studio (from the Dashboard, Studios list, Subscriptions list, or its detail page), click \"Activate\", pick the plan they paid for, and confirm. This is only for cash collected outside the app — card payments activate automatically.",
    relatedArticleIds: ["issuer-activate-cash-sub"],
  },
];
