// Single source of truth for the static public routes' page metadata. Read by the pages (so the
// client-side <title>/description match) AND by scripts/prerender-meta.ts (so the raw HTML served
// for each route carries the same metadata). Dependency-free and erasable-syntax only: Node 24
// runs it directly via type stripping, so it must not import anything (no "@/" aliases).
//
// SITE_URL here must equal SITE_URL in src/shared/constants/legalEntity.ts (a unit test asserts it).

export const SITE_URL = "https://tattooos.co";

/** Absolute URL of the default social-preview image (generated by scripts/generate-og-image.mjs). */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-image.png`;

export interface RouteMeta {
  path:        string;
  title:       string;
  description: string;
}

interface RouteText {
  title:       string;
  description: string;
}

// The home page ("/") keeps the defaults in index.html and is not listed here.
export const ROUTE_META = {
  "/features": {
    title: "Features — TattooOS",
    description:
      "Online booking, deposits, digital consent forms, design approvals and client records — everything a tattoo studio needs in one place.",
  },
  "/pricing": {
    title: "Pricing — TattooOS",
    description: "Simple pricing for tattoo studios, with no commission on your bookings.",
  },
  "/use/booking": {
    title: "Online booking for tattoo studios — TattooOS",
    description:
      "Let clients book the artist and time they want, without an account. Availability is checked before a booking is confirmed.",
  },
  "/use/deposits": {
    title: "Tattoo deposits without the chasing — TattooOS",
    description:
      "Set your own deposit rules and take deposits at booking. Deposits go to your studio, with no commission on bookings.",
  },
  "/use/consent-forms": {
    title: "Digital consent forms for tattoo studios — TattooOS",
    description:
      "Clients sign intake and consent forms before their appointment. Each signature is timestamped and stored with the exact wording agreed to.",
  },
  "/faq": {
    title: "FAQ — TattooOS",
    description:
      "Answers to common questions about TattooOS: commission, deposits, consent forms, guest booking and getting started.",
  },
  "/discover": {
    title: "Discover Tattoo Art Near You — TattooOS",
    description: "Browse tattoo portfolios and studios near your location.",
  },
  "/contact": {
    title: "Contact — TattooOS",
    description: "Get in touch with the TattooOS team.",
  },
  "/privacy": {
    title: "Privacy Policy — TattooOS",
    description: "How TattooOS collects, uses, and protects your personal data.",
  },
  "/terms": {
    title: "Terms of Service — TattooOS",
    description: "The terms governing your use of TattooOS.",
  },
  "/refund-policy": {
    title: "Refund Policy — TattooOS",
    description: "How deposits, cancellations, and no-shows are handled on TattooOS.",
  },
} as const satisfies Record<string, RouteText>;

export type StaticRoutePath = keyof typeof ROUTE_META;

export const STATIC_ROUTES: ReadonlyArray<RouteMeta> = (
  Object.entries(ROUTE_META) as Array<[StaticRoutePath, RouteText]>
).map(([path, text]) => ({ path, title: text.title, description: text.description }));
